fluxcd/pkg

gittestserver/go.mod, gittestserver/go.sum
In favour of a pre-release / commit version.
=> gittestserver: drop sosedoff/gitkit replace

actions/helm/action.yml, actions/helm/entrypoint.sh, actions/kubebuilder/action.yml, actions/kubebuilder/entrypoint.sh, actions/kubectl/action.yml, actions/kubectl/entrypoint.sh, actions/kustomize/action.yml, actions/kustomize/entrypoint.sh
=> Add version input to GH Actions

runtime/consts.go
Extract common condition reasons to be used across all toolkit controllers.
=> Add Ready condition to runtime

.github/workflows/build.yaml, Makefile, docs/internal/release.md
Ref: https://github.com/fluxcd/toolkit/issues/152
=> Set main as default branch

version/go.mod, version/go.sum, version/version.go, version/version_test.go
Ref: https://github.com/fluxcd/source-controller/issues/127
=> Introduce `version` package

apis/meta/annotations.go, apis/meta/annotations_test.go, apis/meta/condition_types.go, apis/meta/doc.go, git/provider.go, git/provider_github.go, git/provider_gitlab.go, git/repository.go, gittestserver/server.go, helmtestserver/server.go, runtime/dependency/sort.go, runtime/dependency/sort_test.go, runtime/doc.go, runtime/errors/errors.go, runtime/events/event.go, runtime/events/recorder.go, runtime/events/recorder_test.go, runtime/internal/tarjan/tarjan.go, runtime/predicates/changed.go, ssh/host_key.go, ssh/key_pair.go, testserver/artifact.go, testserver/http.go, version/version.go, version/version_test.go
Ref: https://github.com/fluxcd/toolkit/issues/380
=> Change copyright to Flux authors

runtime/events/recorder.go
=> Correct spelling in string literals

gittestserver/server.go
Add option to run git server with a tls cert.
=> Add ability to start git server with TLS

runtime/metrics/recorder.go
This metric aims to add the possibility to alert when resources are suspended for too long.
=> Add gotk_suspend_status metric

git/go.mod, git/go.sum, git/provider_gitlab.go
Ref: [flux#674](https://github.com/fluxcd/flux2/issues/674)
=> Search subgroups in gitlab

git/provider.go, git/provider_github.go, git/provider_gitlab.go
=> Add GetRepositoryOwner function to Git provider

actions/crdjsonschema/Dockerfile, actions/crdjsonschema/action.yml, actions/crdjsonschema/entrypoint.sh, actions/crdjsonschema/openapi2jsonschema.py, generated/buckets.source.toolkit.fluxcd.io-crd.yaml, generated/gitrepositories.source.toolkit.fluxcd.io-crd.yaml, generated/helmcharts.source.toolkit.fluxcd.io-crd.yaml, generated/helmrepositories.source.toolkit.fluxcd.io-crd.yaml, source-controller.crds.yaml
Ref: https://github.com/fluxcd/flux2/discussions/408
=> Add GH Action to generate OpenAPI JSON schema from Kubernetes CRD

apis/meta/conditions.go, apis/meta/go.sum
This pull request adds the `Stalled` and `Reconciling` condition to the meta.
=> Add stalled and reconciling condition

.github/workflows/build.yaml, actions/envtest/action.yml
Use [Envtest binaries manager](https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest) to prep the GH runner.
=> Add controller runtime envtest GH action

Makefile
This adds setup-envtest in the Makefile to make it easier to run
envtests without the need to download the kubebuilder binaries
separately.
The default value of KUBEBUILDER_ASSETS can be overridden by the value
set in CI, actions/envtest github action.
Signed-off-by: Sunny <darkowlzz@protonmail.com>
=> Add setup-envtest in Makefile

runtime/predicates/reconcile_requested_test.go
Adds unit tests for ReconcileRequestedPredicate.Update.
=> runtime/predicates: Add unit tests

helmtestserver/go.mod, helmtestserver/go.sum
Supersedes #135 
Fix for CVE-2021-32690
=> Update helm pkg to v3.6.3

.github/workflows/scan.yaml
=> Enable code scanning

runtime/acl/acl.go, runtime/acl/acl_test.go, runtime/acl/doc.go, runtime/go.mod
Ref: https://github.com/fluxcd/flux2/issues/1704
=> Add ACL authorization helper to runtime

runtime/patch/patch.go
At present the example of how to use patch.Helper unconditionally clears the reconciling condition on a "clean" exit (no error or explicit requeue). This is on the assumption that the condition is used only within the Reconcile method to indicate that the resource is being processed.
However, in general it's possible for Reconcile to exit cleanly without the reconciliation having reached a ready state, but without definitively failing either. For example, a Deployment would need to visit Reconcile several times during a rolling upgrade before it has rolled out a new pod spec.
On the expectation that people may borrow the example, I think it is better to treat the Reconciling condition as an indication that there is more work to be done.
=> Account for reconciling condition in patch example

ssa/manager_delete.go
Ref: https://github.com/fluxcd/kustomize-controller/issues/440
=> ssa: Set delete propagation policy to background

ssa/manager_apply.go, ssa/manager_apply_test.go
Skip applying changes to in-cluster objects when their metadata (labels and/or annotations) match the exclusions list.
=> ssa: Add exclusions to apply options

ssa/sort.go
Currently the apply order of the native Kubernetes kinds matches kubectl. This PR extract the kinds into a global variable so that consumers can diverge from kubectl ordering if they wish so.
=> ssa: Allow consumers to override the apply order

ssa/sort.go
=> ssa: Fix apply order override

.github/actions/run-tests/Dockerfile, .github/actions/run-tests/action.yml, .github/workflows/build.yaml
Run the build inside a container
=> Run build in container

ssa/manager_apply.go, ssa/manager_apply_test.go, ssa/manager_wait_test.go, ssa/utils.go
We want to rely on this function behavior in flux-cli
Signed-off-by: Soule BA <bah.soule@gmail.com>
=> Export IsImmutableError, and some clean-up

actions/sbom/action.yml
=> Add checksum verification for syft installer script

kustomize/kustomize_generator.go
If implemented this will permit consuming the Action type from other
packages.
Signed-off-by: Soule BA <bah.soule@gmail.com>
=> Export the Action type in pkg/kustomize

.github/workflows/actions.yaml, actions/sops/action.yaml
If implemented, this code will enable flux packages to use this action to run sops
commands.
Signed-off-by: Soule BA <bah.soule@gmail.com>
=> Add a github action for sops

ssa/manager_diff.go, ssa/manager_diff_test.go
Ref: https://github.com/fluxcd/flux2/pull/2167#issuecomment-1017276463
=> ssa: Add exclusion list to diff options

runtime/acl/flags.go
Part of: https://github.com/fluxcd/flux2/issues/2337
=> runtime: Add flag to disable cross-namespace refs

.github/workflows/build.yaml, .gitignore, Makefile, runtime/acl/acl.go, runtime/acl/acl_test.go, runtime/acl/doc.go, runtime/acl/flags.go, runtime/go.mod, runtime/go.sum
Cherry-pick `runtime/acl` to `runtime/0.12.x` branch.
=> Add runtime/acl package - (runtime/0.12.x)

ssa/manager_diff_test.go, ssa/testdata/test7.yaml
=> ssa: Add tests for metadata drift detection

runtime/features/features.go, runtime/features/features_test.go, runtime/go.mod, runtime/go.sum
Adds `features.FeatureGates` that acts as an helper to managing feature switches.
Controllers can set their supported features and then at runtime verify which ones are enabled/disabled.
Callers have to call `BindFlags()`, and then call `SupportedFeatures()` to set the supported features and their default values.
Example usage for source-controller:
```golang
import (
feathelper "github.com/fluxcd/pkg/runtime/features"
"github.com/fluxcd/source-controller/internal/features"
)
...
var featureGates feathelper.FeatureGates
...
featureGates.BindFlags(flag.CommandLine)
flag.Parse()
err := featureGates.WithLogger(setupLog).
SupportedFeatures(features.FeatureGates())
if err != nil {
setupLog.Error(err, "unable to load feature gates")
os.Exit(1)
}
```
```golang
// Package features sets the …
```
=> runtime: Add Feature Gates

.github/workflows/actions.yaml, .github/workflows/build.yaml, .github/workflows/cifuzz.yaml, .github/workflows/ossf.yaml, .github/workflows/scan.yaml
Publish scorecards to OSSF weekly.
=> Add OSSF Scorecards action

ssh/knownhosts/known_key_test.go
=> Add tests for `ParseKnownHosts` and `KnownKey.Matches`

kustomize/go.mod, runtime/go.mod
Bump `apis` in `runtime` and `kustomize` packages.
=> Update internal dependencies

kustomize/go.mod, runtime/go.mod
Bump apis/meta and apis/kustomize
=> Update runtime to latest apis

masktoken/masktoken.go, masktoken/masktoken_test.go
Ref: https://github.com/fluxcd/pkg/pull/289#discussion_r896826660
=> maskToken: Return regex compile error 

.github/workflows/build.yaml, kustomize/filesys/fs_secure_test.go
Fixes #275 
Fixes #294 
This pull request also modifies the GitHub workflow to run the tests on MacOs.
=> kustomize: Fix failing tests on MacOS

oci/client/build.go, oci/client/build_test.go, oci/client/testdata/artifact/somedir/git/repo.yaml
=> Check for `.` path before using domain

oci/client/list.go, oci/client/list_test.go, oci/go.mod, oci/go.sum
Part of: [flux2/#2983](https://github.com/fluxcd/flux2/issues/2983)
=> [pkg/oci]: Add options to filter tags by semver and regex

oci/client/list.go, oci/client/list_test.go
=> [pkg/oci] Export fields in ListOptions

oci/client/internal/fs/fs_test.go
=> [pkg/oci] Remove test symlink dir

oci/client/delete.go, oci/client/delete_test.go
Part of: [fluxv2/#2983](https://github.com/fluxcd/flux2/issues/2982)
=> [pkg/oci]: Add Delete function

Makefile, apis/acl/go.mod, apis/kustomize/go.mod, apis/meta/go.mod, git/go.mod, git/gogit/go.mod, git/internal/e2e/go.mod, git/libgit2/go.mod, gittestserver/go.mod, gitutil/go.mod, helmtestserver/go.mod, http/transport/go.mod, kustomize/go.mod, lockedfile/go.mod, masktoken/go.mod, runtime/go.mod, ssa/go.mod, ssh/go.mod, testserver/go.mod, untar/go.mod, version/go.mod
Part of: https://github.com/fluxcd/flux2/issues/2696
=> Update Go to v1.18 in go.mod

.github/workflows/e2e.yaml, git/internal/e2e/github_test.go, git/internal/e2e/go.mod, git/internal/e2e/go.sum, git/internal/e2e/run.sh, git/internal/e2e/utils.go
Add e2e tests for https://github.com. Modify CI to run git e2e tests only when there are changes to the `git/` directory.
Partially addresses #330
=> Add e2e tests for GitHub

.github/workflows/build.yaml, .github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/scan.yaml, Makefile, apis/meta/annotations.go, gittestserver/server.go, kustomize/go.mod, kustomize/kustomize_generator.go, runtime/conditions/merge.go, runtime/conditions/unstructured.go, runtime/controller/metrics.go, runtime/events/recorder.go, runtime/events/recorder_fuzzer_test.go, runtime/go.mod, runtime/patch/patch.go, runtime/pprof/pprof.go, runtime/predicates/reconcile_requested.go, runtime/probes/probes.go, runtime/testenv/testenv.go, ssa/manager.go
Changes:
- update CI to use Go 1.19
- bump internal packages
=> Update Go and internal packages

.github/workflows/e2e.yaml, git/internal/e2e/gitlab_ce_test.go, git/internal/e2e/gitlab_test.go, git/internal/e2e/go.mod, git/internal/e2e/go.sum, git/internal/e2e/run.sh
Add e2e git tests for https://gitlab.com.
=> Add e2e tests for GitLab

git/libgit2/transport/http.go, git/libgit2/transport/ssh.go
=> git/libgit2: log context closed message as info instead of err

oci/client/build.go, oci/client/build_test.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
_https://github.com/fluxcd/flux2/discussions/3176_
/cc @stefanprodan
=> feat: accept files in oci build

http/fetch/go.mod, oci/go.mod
=> Update tar pkg for `http/fetch` and `oci/client`

oci/client/diff.go, oci/client/diff_test.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Part of: https://github.com/fluxcd/flux2/issues/3194
/cc @stefanprodan
=> oci/client: add diff capability

git/gogit/repository_client.go, git/gogit/repository_client_test.go
When force push is enabled, we always override the push branch therefore references for the target branch are redundant.
By short-circuting the process, we avoid a fetch operation against the server, which in this case has no impact on the end result.
For servers that require `multi_ack`, this operation was leading to a silenced error.
=> gogit: Optimise force push

.github/workflows/ossf.yaml
=> Bump scorecard action to v2.0.6

.github/workflows/e2e.yaml
=> ci: fix git e2e tests workflow

actions/crdjsonschema/openapi2jsonschema.py
=> Fix openapi2jsonschema action

git/internal/e2e/bitbucket_server_test.go
=> git/e2e: fix bitbucket server url parsing and project key

oci/client/build.go, oci/client/build_test.go
Part of: https://github.com/fluxcd/flux2/issues/3256
Closes: https://github.com/fluxcd/flux2/issues/3383
This pull request fixes a couple of things in the Build function.
1. An archive built on windows can be pulled/untar properly.
3. We have the same behaviour when absolute and relative directories are passed in as arguments.
Previously, Relative directories had the relative path included in the archive while the absolute directory had only its directories and files included.
Now we include only the directories and files that are contained in the directory for both of them.
4. When a single file is passed as the source, we put this file in the root directory for both relative and absolute file paths
5. Improved and unified tests
Signed-off-by: Somtochi Onyekwere …
=> Build archive properly in oci.Build

Makefile
Pin envtest to Kubernetes v1.25 due to #437
=> Pin envtest to Kubernetes v1.25

git/gogit/client.go
Revert commit 80ff3d5d8206392916216d489260f43b58387da8 due to https://github.com/fluxcd/flux2/issues/3467
=> git/gogit: stop auto-staging files from WithFiles

ssa/manager_apply.go, ssa/patch.go
Fixes https://github.com/fluxcd/pkg/issues/439
Export ssa patching methods
=> feat: export ssa patching methods

.github/workflows/e2e.yaml, git/internal/e2e/README.md, git/internal/e2e/bitbucket_server_test.go, git/internal/e2e/github_test.go, git/internal/e2e/gitlab_ce_test.go, git/internal/e2e/gitlab_test.go, git/internal/e2e/run.sh, git/internal/e2e/setup_gitlab.sh
Improve the UX of running tests locally by allowing for more user configuration via env vars.
Add README with information about tests and steps on how to run them for each provider.
=> git/e2e: improve UX and add README

ssa/manager_apply.go, ssa/manager_apply_test.go
Add `ForceSelector` to `ApplyOptions` to recreate immutable objects with matching labels or annotations.
Ref: https://github.com/fluxcd/flux2/discussions/3433
=> ssa: Add force apply selector options

oci/tests/integration/.env.sample, oci/tests/integration/README.md
Add details about using Service Principal for azure tests.
=> oci/tests: Add details about using Azure Service Principal for authentication

ssa/utils.go
Make the JSON object retuned by `ssa.ObjectsToJSON ` compatible with `kubectl apply`.
=> ssa: Use List v1 as JSON output

ssa/manager_apply.go, ssa/manager_apply_test.go, ssa/testdata/test1.yaml
Closes https://github.com/fluxcd/flux2/issues/3627
=> [pkg/ssa] Do not force apply if resource doesn't exist on the cluster

git/go.mod, git/go.sum, gittestserver/go.mod, gittestserver/go.sum, kustomize/go.mod, kustomize/go.sum, oci/go.mod, oci/go.sum, oci/tests/integration/go.mod, oci/tests/integration/go.sum, runtime/go.mod, runtime/go.sum, ssa/go.mod, ssa/go.sum
Part of: https://github.com/fluxcd/flux2/issues/3907
=> Update controller-runtime from beta to v0.15.0

oci/client/list.go, oci/client/list_test.go
Cosign uses "special" tags that have the following naming format:
```    
<digestAgorithm>-<digestHex>.<artifactType(.att, .sbom, .sig)>
```
These are used to attach attestations, SBOMs and signatures to a  subject image reference by the first portion of the tag.
Until now Flux would ignore `.sig` tags, as its primary goal is to filter through app image versions. This change extends the list of omitted cosing artifacts to cover `.att` and `.sbom`.
In some cases it's desirable to observe cosgin artifacts, e.g. in order to determine wheather an image had been signed or not. Hence this change introduces a new field in `ListOptions`.
=> oci: Improve handling of cosgin artifacts

git/gogit/clone.go
Use `cloneBranch()` and `cloneTag()` when cloning a repo via a refname if the refname points to a branch/tag. This enables shallow cloning repositories via refnames as `cloneCommit()` doesn't support shallow cloning.
Fixes #659
=> git/gogit: use existing methods to clone branch/tag via refname

actions/kustomize/action.yml
=> Bump kustomize GH Action to 5.3.0

ssa/normalize/normalize.go, ssa/normalize/normalize_test.go
Implement workaround for Kubernetes upstream bug, fix: https://github.com/fluxcd/kustomize-controller/issues/1041
=> ssa: Skip normalization of Roles and ClusterRoles

helmtestserver/go.mod, helmtestserver/go.sum, oci/go.mod, oci/go.sum, oci/tests/integration/go.mod, oci/tests/integration/go.sum
=> Update docker dependencies

git/gogit/go.mod, git/internal/e2e/go.mod, kustomize/go.mod, oci/go.mod, oci/tests/integration/go.mod, runtime/go.mod, runtime/go.sum
=> Update internal packages

kustomize/kustomize_varsub.go
Part of: https://github.com/fluxcd/flux2/issues/5109
=> Make the variables loading function public

apis/event/v1beta1/metadata.go
Part of: https://github.com/fluxcd/flux2/issues/5148
=> Add MetaOriginRevisionKey to Event API

apis/event/v1beta1/event.go
Part of: https://github.com/fluxcd/flux2/issues/5148
=> Add GetRevision() to Event API

.github/workflows/integration-aws.yaml, .github/workflows/integration-azure.yaml, .github/workflows/integration-gcp.yaml, oci/tests/integration/.env.sample, oci/tests/integration/README.md, oci/tests/integration/azure_test.go, oci/tests/integration/git_test.go, oci/tests/integration/go.mod, oci/tests/integration/job_test.go, oci/tests/integration/oci_test.go, oci/tests/integration/suite_test.go, oci/tests/integration/terraform/aws/variables.tf, oci/tests/integration/terraform/azure/main.tf, oci/tests/integration/terraform/azure/outputs.tf, oci/tests/integration/terraform/azure/variables.tf, oci/tests/integration/terraform/gcp/main.tf, oci/tests/integration/terraform/gcp/variables.tf, oci/tests/integration/testapp/main.go
=> [RFC-0010] Add integration tests for object-level workload identity

auth/azure/implementation.go, auth/azure/implementation_test.go, auth/azure/new_default_azure_credential.go, auth/azure/provider.go, auth/azure/provider_test.go, auth/get_token.go, auth/get_token_test.go, auth/options.go
xref: https://github.com/fluxcd/flux2/issues/5375
=> Introduce support for shelling out to Azure binaries in authentication

runtime/secrets/factory.go, runtime/secrets/factory_test.go
Add `MakeSOPSSecret` that would enable us to add a new command to Flux CLI `flux create secret sops`.
=> runtime/secrets: Add `MakeSOPSSecret`

git/github/client.go, git/github/client_test.go, git/gogit/go.mod, git/internal/e2e/github_test.go, git/internal/e2e/go.mod, oci/tests/integration/go.mod
Also renaming secret data key symbols to match the project standard.
=> github: Remove redundant options

auth/azure/provider.go, auth/azure/provider_test.go, oci/tests/integration/go.mod
=> [RFC-0010] auth/azure: Support all Azure clouds for remote clusters at the controller level

kustomize/kustomize_generator.go, kustomize/kustomize_generator_test.go
Add option to ignore missing components when generating the `kustomization.yaml` 
ref: https://github.com/fluxcd/kustomize-controller/issues/1440
=> kustomize: Add `ignoreMissingComponents` option

runtime/cel/expression.go, runtime/cel/expression_test.go, tests/integration/go.mod
Planning to use this in the MCP server.
=> runtime/cel: introduce Evaluate()

ssa/manager_diff.go
Part of: https://github.com/fluxcd/flux2/issues/3032
=> ssa: Add force apply config to dry-run diff
