- recorder/event.go
- recorder/recorder.go
Add reporting instance field to the event struct and set it to hostname in event recorder.
> Add reporting instance field to Event

- untar/LICENSE
- untar/untar.go
The untar package can be used to extract source artifacts.
Adapted from golang.org/x/build/internal/untar
> Add untar utility

- actions/helm/Dockerfile
- actions/helm/action.yml
- actions/helm/entrypoint.sh
- actions/kubebuilder/Dockerfile
- actions/kubebuilder/action.yml
- actions/kubebuilder/entrypoint.sh
- actions/kubectl/Dockerfile
- actions/kubectl/action.yml
- actions/kubectl/entrypoint.sh
- actions/kustomize/Dockerfile
- actions/kustomize/action.yml
- actions/kustomize/entrypoint.sh
{kustomize,helm,source}-controller use almost the same set of actions in their builds. Before we make more copies, this PR centralises the union of the actions here (and subsequent PRs will update the individual repos).
This also standardises the Dockerfiles and entrypoints a little.
> Centralise GitHub Actions definitions used in *-controller builds

- git/go.mod
- git/go.sum
- git/provider.go
- git/provider_github.go
- git/provider_gitlab.go
Changes:
- Update go-github to v32.1.0
- Implement repository delete for GitHub
> Update GitHub pkg and implement repo del

- runtime/errors/errors.go
This PR adds commonly found errors in the toolkit controllers so
that they produce (rich) and consistent error (messages).
> Introduce `errors` to `runtime` package

- .github/workflows/build.yaml
- actions/helm/entrypoint.sh
- actions/kubebuilder/entrypoint.sh
- actions/kubectl/entrypoint.sh
- actions/kustomize/entrypoint.sh
The `add-path` command is deprecated and will be disabled soon.
Switching to using environment files ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Migrate GitHub actions to environment files

- runtime/metrics/recorder.go
In order to align with the [prometheus metric naming guidelines](https://prometheus.io/docs/practices/naming/) which say
that metric names:
> should have a suffix describing the unit, in plural form.
ref: https://github.com/fluxcd/toolkit/issues/329
Note: a follow up would be needed to update the dashboard added in https://github.com/fluxcd/toolkit/pull/337
> Add unit suffix to reconcile duration metric

- apis/meta/annotations.go
- apis/meta/annotations_test.go
- runtime/predicates/changed.go
This adds a new annotation name, as proposed in https://github.com/fluxcd/toolkit/discussions/363, and provides some helpers for
- getting the value in a backward-compatible way
- recording the value in a CRD status field (so as to detect changes).
> Reconcile request annotation and helpers

- runtime/metrics/recorder.go
Looks like I forgot to use metav1.ConditionUnknown instead in the `RecordCondition`. No biggie since it works just fine considering that the stringified value is used.
> Replace reference to corev1.ConditionUnknown

- apis/meta/conditions.go
Handle setting `Status.Conditions` for any resource implementing the `v1.Object` interface. This is common in all flux api types.
According to suggestion in: https://github.com/fluxcd/pkg/pull/48#issuecomment-723154919
> Add SetResourceCondition func to apis/meta

- apis/meta/annotations.go
This improves the generated CRD (and thus API) documentation.
> Mark LastHandledReconcileAt as optional

- runtime/logger/logger.go
> Add copyright header to logger.go

- MAINTAINERS
See https://github.com/fluxcd/flux2/discussions/515.
(NB this one has no maintainers that are not already flux2 maintainers, hence different wording.)
> Share maintainers from fluxcd/flux2

- git/provider_gitlab.go
Ensure projects are discovered using the correct method in the case of group owned projects (ListGroupProjects) vs personal owned projects (ListProjects).
The issue can be reproduced when bootstrapping on GitLab with a personal account and using a repository name that could already belong to another user.
This is from a user report in [slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1607540221358200).
Fixes #22.
> Fix CreateRepository for GitLab provider

- runtime/logger/logger.go
> Make "json" the listed log-encoding default

- runtime/predicates/reconcile_at_changed.go
The logic of the (newly separated) ReconcileAtChanged predicate should
be:
if new object has reconcileAt annotation
if old obj has different or no annotation -> true
else -> false
However the old and new object were swapped around, leading to
if old object has reconcileAt annotation
...
which results in `false` when the annotation has just been applied,
when it should be `true`.
Signed-off-by: Michael Bridgen <michael@weave.works>
> Fix false negatives from reconcile-at predicate

- runtime/predicates/reconcile_at_changed.go
- runtime/predicates/reconcile_requested.go
This changes the name of the predicate (that contained a typo) from
`ReconcilateAtChangedPredicate` to `ReconcileRequestedPredicate`,
which does _not_ contain a typo and is more in-line with the naming
of the `ReconcileRequestAnnotation`.
> Rename predicate to ReconcileRequestedPredicate

- git/provider.go
- git/provider_github.go
- git/provider_gitlab.go
This PR 
1. ensures that the group and subgroup gotten from the GitLab search is the same specified by the user
2. sets the correct gitlab path in the `getProjects` function and removes `getRepositoryOwner` from the interface.
I tested these changes on a self-hosted GitLab instance and I confirm that I fixed the regression bug introduced in [flux#681](https://github.com/fluxcd/flux2/pull/681) that prevented users from using a custom hostname instead of gitlab.com
> Ensure correct group is gotten from gitlab search

- git/provider_gitlab.go
This pull-request checks for the name or the path when finding the group from the search returned by GitLab.
Currently, users of flux v0.6.1, due to this pull request #67, get a `failed to find group` error because we check only the name. In v0.6.next, they will be able to.
Issue ref: [flux2#727](https://github.com/fluxcd/flux2/issues/727)
> GitLab: Check both the name and the path when searching for groups

- apis/meta/reference_types.go
This PR adds structs for being able to reference Kubernetes objects inside the same namespace or across namespaces.
> Add object ref types

- runtime/client/client.go
- runtime/go.mod
- runtime/logger/logger.go
This PR adds helper functions for injecting the `kube-api-qps` and `kube-api-burst` in the GitOps toolkit controllers flags.
The logger flags are now set with `spf13/pflag`.
> Add Kubernetes client options (QPS and Burst) to runtime

- git/provider_gitlab.go
Resolves #75 
I did run a small test vs our local gitlab instance without any issues:
> Drop required access level when listing groups using the GitLab API

- git/go.mod
- git/go.sum
- git/provider_github.go
- google/go-github to v33.0.0
Breaking changes have no impact on us:
https://github.com/google/go-github/releases/tag/v33.0.0
- xanzy/go-gitlab to v0.43.0
> Update `git` dependencies

- git/provider_gitlab.go
During the development of the provider a mistake was made, and the
repository was created using the `Name` field instead of the `Path`.
The result of this is that GitLab will create a `Path` based on the
provided `Name`, with a random (number) suffix added, resulting in
all sorts of issues (and work around attempts) down the line.
By only working with `Path` fields, and assuming that the provided
repository name is a path, the look ups we make are now guaranteed
to always return the same group, subgroup or repository.
> git: drop usage of Name for GitLab operations

- runtime/pprof/pprof.go
This follows the suggestion of controller-runtime to use the metrics
server for registering the handlers using `AddMetricsExtraHandler`.
> Add helper for setting up pprof handlers

- gittestserver/server.go
- gittestserver/server_test.go
The underlying library, gitkit, expects to have a KeyDir supplied in its *Config when running an SSH server. It's uncertain whether StartSSH is used anywhere (and it wouldn't work, if it is); but for the least disruption, I have added a func for supplying the KeyDir value rather than changing the signature of any existing func.
Since StartSSH blocks when it succeeds, the test has to do a kludge with a timer to be able to exit.
`StartSSH()` doesn't return until `StopSSH()` is called (or there's an error). This makes it difficult to use in tests, since you will usually want to know the address to use before proceeding with the rest of the test, but the listener must be created before it can be obtained.
This PR adds a `ListenSSH()`, which creates the SSH server and listener on localhost, …
> Make SSH server usable for testing

- gittestserver/server.go
When testing using gittestserver, it's useful to be able to use
authentication. This is especially true when testing against libgit2,
because it expects authentication over SSH, and will balk if it's not
requested.
This commit adds a method to *GitServer for switching auth on. There's
no way to switch auth on for just SSH -- it will also be required for
HTTP. For that reason, a username and password are needed.
The credentials are included in the URL returned by HTTPAddress(), so
anything using that will transparently work whether auth is on or
not. An alternative would be to let uses of *GitServer provide the
credentials if auth is on; but, it is not always convenient to supply
creds for git over HTTP, so those uses would likely have to all just
recreate the code that puts them in the …
> Add method to GitServer to switch auth on

- runtime/transform/transform.go
- runtime/transform/transform_test.go
Moves `MergeMaps` from [helm-controller](https://github.com/fluxcd/helm-controller/blob/8492473195545b06a133ca42d353946a3bd60b67/internal/util/util.go#L29-L51) (and [flux2](https://github.com/fluxcd/flux2/blob/v0.8.0/internal/utils/utils.go#L403-L404)) to pkg for future use.
I was very lazy and assumed you'd still want to call the package `util` but I know that's kinda discouraged.
Closes #84
> Move MergeMaps from helm-controller

- runtime/metrics/recorder.go
This fix sets the correct gauge in RecordSuspend.
> Uses suspendGuage in RecordSuspend

- runtime/leaderelection/leaderelection.go
This PR adds cmd flags for fine tuning the controller-runtime leader election. To make the leader election more tolerant to transient Kubernetes API outages (rate limits, CNI upgrade, control plane upgrades, etc) the renewal deadline was increased from 10 seconds to one minute and the retry interval was bumped to 5 seconds.
> Add leader election config to runtime

- runtime/leaderelection/leaderelection.go
Follow #92 on a rolling update the `ReleaseOnCancel` has no effect so we need to bring the deadline duration down.
> Set leader election Lease duration to 35s

- runtime/events/recorder.go
- runtime/events/recorder_test.go
Ref: https://github.com/fluxcd/helm-controller/issues/247
> Avoid retrying rate limited events

- ssh/kex.go
Ref: https://github.com/fluxcd/flux2/issues/1320
> Add preferred key algorithms

- runtime/controller/doc.go
- runtime/controller/events.go
- runtime/controller/metrics.go
- runtime/events/event.go
This is an experimental PR to see if some of the bits common to all the GOTK controllers can be factored out into embeddable structs.
Among other things, this will
- reduce duplication
- standardise how these common bits are done
It is a bit rough around the edges:
**You have to supply an ObjectReference to both the metrics and the events methods**. This is because all the constituent bits calculated this for themselves, and had different ways of dealing with errors. This way, the error handling is done once, up front, and the ref only has to be calculated once. But it would be nice to do this behind the scenes, in some way.
**You have to pass logs in to the Events helper**. This is a bit awkward, as getting logs to funcs always is. It'd be nice if the setup could just do this for you.
> Controller helpers

- runtime/go.mod
- runtime/testenv/testenv.go
This adds a tiny wrapper around controller-runtime's `testenv` package
so that the configuration for integration tests becomes much easier.
The work is derived from
https://github.com/kubernetes-sigs/cluster-api/tree/aa049f15e75d3ac715c2a1a1e58d34fa77280eef/internal/envtest
but offers configuration options to setup Custom Resource Definitions
and the runtime scheme in a generic way.
> runtime: add `testenv` integration test util

- runtime/logger/logger.go
Fixes #112, by adding `trace` to the possible log level values.
The underlying logging library, zap, will accept "custom debug levels" (i.e., levels numerically less than debug -- its levels are in ascending order of importance). It logs these with e.g., `LEVEL(-2)`, but there's no way around that. At least the mechanism works.
> Trace log level

- runtime/controller/events.go
While validating the runtime package changes, it quickly become
cumbersome to pass `nil` for every event that didn't require any
metadata to be attached.
This commit solves this annoyance by renaming the existing methods to
`EventWithMeta` and `EventWithMetaf`, and reintroducing the `Event` and
`Eventf` methods with signatures that do not take any metadata string
map.
Fixes #119
> Make it easier to send events without metadata

- runtime/tls/doc.go
- runtime/tls/testdata/keys.go
- runtime/tls/tls.go
- runtime/tls/tls_test.go
This change is meant to standardize how certificates are read from secrets by the controllers. This logic is currently shared by notification-controller and image-reflector-controller, there might be more.
The original logic is taken from image-reflector-controller.
https://github.com/fluxcd/image-reflector-controller/blob/de3de64adddf8bb00276e12aa0436968bc94ff39/controllers/imagerepository_controller.go#L278-L309
I did however make a change to the behavior so that the functions will return an error if the secret does not contain a ca or cert. Or when the client cert is set but not client key and vice versa. My opinion is that this behavior is more logical than the previous one.
> Add TLS package and helper methods to runtime

- runtime/README.md
- runtime/doc.go
- runtime/pprof/pprof.go
> README for runtime package

- runtime/conditions/setter.go
- runtime/conditions/setter_test.go
This is more logical, as both `StalledCondition` and
`ReconcilingCondition` are abnormal-true types, and should thus only be
present on a resource when the condition is True.
> Order ReconcilingCondition before ReadyCondition

- gittestserver/server.go
For testing what a controller does when the git server balks at an operation (e.g., pushing a branch), it's useful to be able to install a service-side git hook in the test git server.
The new method added here is for installing an update hook (runs for each updated ref), which is the one I needed; pre-receive (runs before accepting the push) and post-receive (runs after accepting the push) are trivial adaptations, should they be needed.
NB I have not provided a test for this, because I didn't think the cost of writing out all the steps was worth it to prove that the underlying library (gitkit) does what it says. (I do however rely on it working, in a test for image update automation).
> Add GitServer method for installing an update hook

- gittestserver/server_test.go
Cleanup the temporary directories created by the gittestserver tests.
The tests used to leave behind the test git repo directories:
```console
$ ls /tmp/git-server-test-
git-server-test-032134880/ git-server-test-047540379/ git-server-test-391635912/ git-server-test-715720328/ git-server-test-845366975/
git-server-test-033305159/ git-server-test-093962088/ git-server-test-576842540/ git-server-test-772416423/ git-server-test-939106439/
```
> gittestserver: Cleanup the test git repo dir

- runtime/conditions/getter.go
- runtime/conditions/getter_test.go
- runtime/conditions/setter.go
- runtime/conditions/setter_test.go
- runtime/patch/patch.go
This commit adds getter and setter helpers to `runtime/conditions` to
make it easier to mark resources with kstatus conditions, and observe
their state.
- The `MarkReconciling` and `MarkStalled` functions delete their
counterpart condition type while marking the resource with the
kstatus condition, making it easier to adhere to the kstatus
standards.
- The `IsReady`, `IsStalled` and `IsReconciling` functions take the
existence of their counterpart condition types into account, ensuring
conclusive conditional checks.
`MarkReady` was not taken into consideration, it could technically be
added as syntax sugar, but this would first require a discussion about
a counterpart as you likely want to be able to mark something as "not
ready".
To determine a Ready condition at present, the advice is …
> runtime/conditions: add kstatus condition helpers

- actions/envtest/Dockerfile
- actions/envtest/action.yml
- actions/envtest/entrypoint.sh
Update action/envtest to be a docker container action. This helps
install envtest binaries without Go installed on the host.
Refer: https://github.com/fluxcd/source-controller/pull/404
> actions/envtest: Update to docker container action

- actions/kubebuilder/entrypoint.sh
Caused by https://github.com/kubernetes-sigs/kubebuilder/issues/2311
Fix was found here: https://github.com/operator-framework/operator-lifecycle-manager/pull/2335/files
> Fix kubebuilder download URL

- CONTRIBUTING.md
- gittestserver/server.go
- gittestserver/server_test.go
- helmtestserver/server.go
- lockedfile/lockedfile.go
- runtime/events/recorder_test.go
- testserver/artifact.go
- testserver/http.go
- testserver/http_test.go
Remove deprecated calls and replace with suggestions from the deprecation notice.
Update test instructions since `make test` doesn't work. Now uses `make all`, which runs tests for all targets in all subdirectories.
Issue: https://github.com/fluxcd/flux2/issues/1658
> Remove use of deprecated io/ioutil package

- runtime/conditions/merge.go
- runtime/conditions/merge_strategies.go
- runtime/conditions/merge_test.go
Adds merge option `WithGenerations()` to consider the condition's observed
generation while merging. When withGenerations is set, the condition
groups are created based on the generation of the conditions. The
condition groups with the latest generations are grouped together and
sorted based on their merge priority. The condition groups with old
generations don't contain the up-to-date information and hence not
considered.
The merge behavior remains the same when no generation is specified.
Fixes #142
> runtime/conditions: Add merge option with generations

- runtime/testenv/testenv.go
This change allows test environments with glog to work with testenv.
image-reflector-controller uses badger for database. [dgraph-io/badger](https://github.com/dgraph-io/badger) go package depends on  [dgraph-io/ristretto](https://github.com/dgraph-io/ristretto), which depends on glog. When glog is used, it sets `log_dir` flag, [refer](https://github.com/golang/glog/blob/23def4e6c14b4da8ac2ed8007337bc5eb5007998/glog_file.go#L41) .
Due to the glog transitive dependency of badger, when badger is used in testenv based tests, the testenv package init() initialization of the klog flags and badger set the glog flags conflict, resulting in some redefined flags.
This can be reproduced by adding the following in `TestMain()`:
```golang
badgerDir, err := ioutil.TempDir(os.TempDir(), "badger")
if …
```
> testenv: Remove klog init flags

- runtime/acl/acl.go
- runtime/acl/acl_test.go
The return type of HasAccessToRef() is `(bool, error)`, but the error is used to signal both a negative result (no access!) and a failure to complete the check (client request failed), leaving the `bool` redundant.
As a result, it's not clear to the caller whether it should report that access was denied, or that there was some (probably transitory) problem.
~Instead, use the bool to signal whether access was possible, and only return an error when there was an error while checking.~
EDIT: return a special type of error for access denied, and remove the bool return value.
> Rationalise the return value of ACL checks

- gittestserver/server.go
- gittestserver/server_test.go
- runtime/acl/acl_test.go
Add http middleware support to be able to change the behavior of the
git server. Usage could be for returning certain response and error or
introducing some delay in the server, etc.
The middlewares can be chained together based on the needs.
Helper middlewares can be added in the future for certain behaviors
frequently needed in tests.
> gittestserver: Add http middleware support

- apis/kustomize/kustomize_types.go
The Kustomize Patch API type only supports inlined patch
definitions and does not support reading patches from a
file. Updating the godoc comments for the type to remove
any mention of reading patch definitions from a file and
make it clear that only inline patches are supported.
> Remove file support from Kustomize Patch type docs

- actions/kustomize/action.yml
When curl fails there has been no way to understand why because of the
'silent' flag. Removing the silent flag and just disabling the
progress meter makes it easier to reason about failures when
downloading kustomize.
[This workflow](https://github.com/fluxcd/helm-controller/runs/4224469169?check_suite_focus=true) has failed for an unknown reason, very probably because the download of kustomize failed:
```
VERSION=4.1.3
ARCH=amd64
REPO_URL=https://github.com/kubernetes-sigs/kustomize/releases/download
BIN_URL="${REPO_URL}/kustomize%2Fv${VERSION}/kustomize_v${VERSION}_linux_${ARCH}.tar.gz"
curl -sL ${BIN_URL} -o /tmp/kustomize.tar.gz
mkdir -p /tmp/kustomize
tar -C /tmp/kustomize/ -zxvf /tmp/kustomize.tar.gz
sudo cp /tmp/kustomize/kustomize /usr/local/bin
rm -rf /tmp/kustomize/ …
```
> feat: make it easier to debug kustomize action failures

- actions/crdjsonschema/Dockerfile
- actions/crdjsonschema/action.yml
- actions/crdjsonschema/entrypoint.sh
- actions/crdjsonschema/objectmeta-meta-v1.json
- actions/crdjsonschema/openapi2jsonschema.py
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>
This PR modifies the `crdjsonschema` action by:
- adding metadata schema to each CRD schema, so that it can be auto-complete when required by editors/IDEs
- adding enum, and default values to apiVersion and kind properties, so that the editors/IDEs know how to pick the correct schema for validation
- adding oneOf operator
The generated schemas have been tested on VS Code.
How to test:
https://github.com/chanwit/flux-json-schemas/blob/main/README.md
> Generate a combined json schemas with oneOf operator

- actions/crdjsonschema/openapi2jsonschema.py
As this is where the `Dockerfile` copies the file to, which differs
(apparently) from the path the Python script is executed in.
> Use `objectmeta-meta-v1.json` from root

- ssa/manager_apply_test.go
- ssa/testdata/test1.yaml
- ssa/utils.go
Ref: https://github.com/fluxcd/kustomize-controller/issues/506
> ssa: Force apply on invalid and conflict errors

- ssa/changeset.go
- ssa/manager_diff.go
- ssa/manager_diff_test.go
Remove the YAML diff composed with go-cmp as the output is not human readable. The `ssa.Diff` now returns the live object and the merged one (resulted from apply dry-run). Consumers can take the two objects and perform the YAML diff with 3rd party tools like Linux `diff` or  https://github.com/homeport/dyff.
> ssa: Remove YAML diff

- runtime/go.mod
Update apis packages to match Go 1.17 and controller-runtime 0.11.0
> Prepare runtime v0.13.0-rc.6

- ssa/manager_diff.go
- ssa/manager_diff_test.go
- ssa/testdata/test6.yaml
- ssa/utils.go
This PR implements a workaround for a Kubernetes API server-side apply dry-run bug where it duplicates the first item in the metrics array and inserts an empty metric as the last item in the array.
Given:
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
name: frontend
namespace: default
spec:
behavior:
scaleDown:
policies:
- periodSeconds: 15
type: Percent
value: 100
selectPolicy: Max
stabilizationWindowSeconds: 60
scaleUp:
policies:
- periodSeconds: 15
type: Pods
value: 4
- periodSeconds: 15
type: Percent
value: 100
selectPolicy: Max
stabilizationWindowSeconds: 0
maxReplicas: 30
metrics:
- type: Pods
pods:
metric:
name: nginx_http_requests_total
target:
averageValue: "4"
type: AverageValue
minReplicas: 2
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment …
```
> Workaround for HPA dry-run metrics duplication

- ssa/manager_diff.go
- ssa/utils.go
- ssa/utils_test.go
This enable an existing secret object and its updated version to preserve changes when masking sensitive values
Signed-off-by: Soule BA <bah.soule@gmail.com>
> Preserve value difference when masking secret data

- ssh/go.mod
- ssh/go.sum
Ref https://groups.google.com/g/golang-announce/c/ouZIlBimOsE?pli=1
> Update golang.org/x/crypto to fix CVE-2020-29652

- .github/workflows/build.yaml
- .gitignore
- Makefile
Refactor logic to install helper tools into one function in the
Makefile. Add support for envtest to help install tools like kubectl,
etcd which helps users run tests more conveniently.
Ref: https://github.com/fluxcd/flux2/issues/2273
> Fix makefile envtest and controller-gen usage

- .github/workflows/cifuzz.yaml
- Makefile
- tests/fuzz/events_fuzzer.go
- tests/fuzz/oss_fuzz_run.sh
Changes:
- Fix issues happening at [oss-fuzz](https://github.com/google/oss-fuzz/runs/4804502678?check_suite_focus=true) blocking https://github.com/google/oss-fuzz/pull/7131.
- Use the project specific smoke test to ensure the fuzzer correctness instead of using the official oss-fuzz GitHub action, which does not support well the multi-repository approach that FluxCD requires.
> Fix fuzzer build and improve fuzz tests on pull requests

- ssa/utils.go
We need to exclude the status sub-resource before server-side apply because the dry-run fails on older Kubernetes versions. Ref: https://github.com/fluxcd/kustomize-controller/issues/532
> Exclude the status subresouce from the applied resource

- .github/workflows/actions.yaml
- actions/sbom/action.yml
This action should be used in all the GitOps Toolkit controllers, in the release workflow, to publish SBOM to GitHub releases.
> Add action to generate SBOM for container images

- ssa/manager_apply.go
- ssa/manager_apply_test.go
- ssa/patch.go
> Replaces kubectl field managers with the resource manager owner in ssa apply

- ssa/utils.go
- ssa/utils_test.go
This PR adds a function for reading Kubernetes objects from an YAML stream that validates if the given resources conform to the Kubernetes API conventions.
Ref: https://github.com/fluxcd/kustomize-controller/issues/542
> ssa: Add read function that validates resources

- ssa/manager_apply.go
- ssa/manager_apply_test.go
- ssa/manager_diff.go
- ssa/patch.go
- ssa/utils.go
- ssa/utils_test.go
Changes:
- use `DeepEqual` to detect drift in metadata maps
- fix typo in `FieldManager` API
- remove `ReadKubernetesObjects` function (static validation should happen before SSA)
> ssa: Refactor server-side apply helpers

- runtime/events/recorder.go
- runtime/events/recorder_test.go
- Handle empty webhook address passed to the event recorder by skipping attempts to post the event to external event endpoint.
- Log events when debug logs are enabled. This is part of simplifying logs and events by making events as the front-end/go-to option. With this, while debugging, the events are also visible in the logs.
> runtime/events: Handle empty webhook address and log event in debug mode

- ssa/go.mod
- ssa/manager_apply.go
- ssa/manager_apply_test.go
- ssa/patch.go
- ssa/testdata/test8.yaml
- ssa/testdata/test9.yaml
This pull request allows the designated manager to transfer ownership of fields from others managers to itself. Instead of replacing a 3rd party manager, we merge the fields into our manager allowing it to take ownership of fields that it previously didn't owned.
Ref:  [#fluxcd/kustomize-controller](https://github.com/fluxcd/kustomize-controller/issues/558).
> ssa: Transfer the ownership of managed fields from others managers

- ssa/utils.go
We can't remove the status sub-resource from CRDs because `kstatus` wait doesn't work with empty status fields 😢 
Ref: https://github.com/fluxcd/flux2/issues/2351
> ssa: Preserve the status field on CRDs

- runtime/patch/patch.go
- runtime/patch/utils.go
- runtime/patch/utils_test.go
`ToUnstructured()` is useful for others controllers, especially for use
in tests.
> runtime/patch: Make ToUnstructured() public

- runtime/client/client.go
Ref: https://github.com/fluxcd/helm-controller/pull/422
> runtime: Increase client QPS and Burst to 50/100

- ssa/go.mod
- ssa/go.sum
- ssa/manager_apply.go
- ssa/manager_apply_test.go
This PR offers an alternative to preventing Flux from overriding kubectl edits. There are cases when setting a different manager for kubectl is not possible (e.g. [EKS CoreDNS](https://fluxcd.io/docs/faq/#how-to-patch-coredns-and-other-pre-installed-addons)), and thus patching existing objects is not possible. With this PR, users can set an annotation to existing objects to hint at Flux that it should skip the kubectl manager takeover.
> ssa: Allow objects to be excluded from metadata cleanup

- helmtestserver/go.mod
- helmtestserver/server.go
- helmtestserver/server_test.go
- helmtestserver/testdata/helmchart/.helmignore
- helmtestserver/testdata/helmchart/Chart.yaml
- helmtestserver/testdata/helmchart/templates/NOTES.txt
- helmtestserver/testdata/helmchart/templates/_helpers.tpl
- helmtestserver/testdata/helmchart/templates/deployment.yaml
- helmtestserver/testdata/helmchart/templates/tests/test-connection.yaml
- helmtestserver/testdata/helmchart/values.yaml
Adds a new method `PackageSignedChartWithVersion` which generates a PGP keypair and uses it to sign the packaged chart, along with a minor refactor. Adds tests for `helmtestserver`.
> Update `helmtestserver` to optionally sign packaged charts

- Makefile
- gittestserver/server.go
Enables race condition checks during the execution of tests. This PR also fixes the only occurrency of racy condition found.
May relate to the `TestGitRepositoryReconciler_reconcileSource_authStrategy` [failures](https://github.com/fluxcd/source-controller/runs/5578047164?check_suite_focus=true) in https://github.com/fluxcd/source-controller/pull/615.
> build: enable '-race' for 'go test' 

- runtime/client/kubeconfig.go
- runtime/client/kubeconfig_test.go
Adds kubeconfig sanitisation for kubeconfig values, making it easier to enforce what features to enabled/disable.
> Add kubeconfig into `runtime/client`

- runtime/conditions/setter.go
- runtime/conditions/setter_test.go
Conditions `Set()` should update the observed generation of the condition
to the latest object version to reflect the observation on the latest
generation of the object.
> runtime/conditions: Update observed gen on Set()

- runtime/controller/rate_limiter.go
Add two new flags to enable users to configure exponential back-off retry. 
The default values are set to 750ms for minimum retry time, and 15min for max.
> runtime/controller: add flags to configure exponential back-off retry

- runtime/go.mod
This wasn't done for `apis/meta v0.12.1`. We really need to keep internal deps in sync, maybe some check in GH Actions would help.
> Bump apis/meta in runtime

- kustomize/filesys/fs_secure.go
- kustomize/filesys/fs_secure_test.go
This implementation functions as a drop-in replacement for Kustomize's
own `fsOnDisk`, and asserts any path it handles to be inside root.
In essence, the whole file system is now restricted like
loader.RestrictionRootOnly would, but while allowing root to differ
from the top Kustomization directory.
The main reason to put the constraint in the file system implementation
is because the current Krusty API does not allow to configure a custom
load restrictor, but does allow injecting a custom FS.
> kustomize: introduce secure FS implementation

- ssh/go.mod
- ssh/go.sum
- ssh/kex.go
Aligns preferred algorithms with upstream golang.org/x/crypto/ssh, resulting in adding support to two new kex algorithms on PreferredKexAlgos:
- curve25519-sha256
- diffie-hellman-group14-sha256
Removes references to unused algorithms that are no longer recommended for use:
- diffie-hellman-group1-sha1
- diffie-hellman-group-exchange-sha1
This code does not seem to be called anywhere. An alternative change may be to simply removing it from the module so we don't need to update it going forwards.
> ssh: Update PreferredKexAlgos based on golang.org/x/crypto/ssh 

- runtime/client/client.go
- runtime/go.mod
- runtime/go.sum
Checks if the PriorityAndFairness flow control filter is enabled to
disable client side throttling, leveraging server side throttling
instead, since client-go respects the `Retry-After` response header set
by the APF filter.
Fixes: #269 
> runtime: Use server-side throttling when available

- ssh/knownhosts/known_key.go
- ssh/knownhosts/known_key_test.go
This PR refactors the known hosts parsing and matching logic from the source-controller into pkg, for easier usage.
> Add helpers to parse knownhosts and match against them

- ssh/knownhosts/known_key.go
- ssh/knownhosts/known_key_test.go
Previously, `KnownKey.Matches()` accepted a SHA256 hasher as an argument,
which could lead to unintended bugs when calling it in a loop. This
eliminates that, by intializing a new hasher itself instead of relying
on the caller for the same.
Enables us to fix a regression in the source-controller: https://github.com/fluxcd/image-automation-controller/issues/378
> Update `KnownKey.Matches` to initialize it's own hasher

- masktoken/go.mod
- masktoken/masktoken.go
- masktoken/masktoken_test.go
This pull requests adds a pkg for masking a token in the string.
The code was moved from [the notification-controller](https://github.com/fluxcd/notification-controller/blob/main/internal/server/event_handlers.go#L322) to be used by other controllers.
> Add pkg for masking token

- .github/workflows/e2e.yaml
- git/e2e/gitkit_test.go
- git/e2e/gitlab_test.go
- git/e2e/run.sh
- git/e2e/setup_gitlab.sh
- git/e2e/setup_gitlab_pat.rb
- git/e2e/utils.go
Refactors the e2e tests to be more cleaner and readable. 
Adds e2e tests for GitLab using https://hub.docker.com/r/gitlab/gitlab-ce/.
Introduces a new CI workflow for e2e tests exclusively. The e2e tests now use build tags to make sure they don't run alongside unit tests.
> git: add E2E tests for GitLab and a separate CI workflow for E2E tests

- git/go.mod
- git/go.sum
- gittestserver/go.mod
- gittestserver/go.sum
- gittestserver/server.go
Pushing using the file protocol on Windows is broken for go-git (ref: https://github.com/go-git/go-git/issues/415). This PR adds support for initializing repos for the test server on Windows by using HTTP.
> Use HTTP server to initialize repos on Windows

- Makefile
- oci/client/list.go
- oci/client/list_test.go
- oci/client/meta.go
- oci/client/push.go
- oci/client/push_pull_test.go
- oci/constants.go
Set the created date annotations when pushing OCI artifacts.
> Add `org.opencontainers.image.created` to OCI meta

- oci/client/internal/fs/fs_test.go
- oci/client/internal/fs/testdata/symlinks/invalid-symlink
- oci/client/internal/fs/testdata/symlinks/windows-file-symlink
The broken symlinks used for tests broke the use of fluxcd/pkg as a GitHub action, as pointed out in:
https://github.com/fluxcd/flux2/pull/2964\#discussion_r939991220
This creates and removes such symlinks on demand to ensure the tests are still catered for, without impacting the GitHub actions.
> oci: Fix broken action

- .github/workflows/cifuzz.yaml
- tests/fuzz/Dockerfile.builder
- Upgrade fuzz container to Go 1.18.
- Upgrade worker to Go 1.18.
> fuzz: Ensure Go 1.18 for fuzz image

- tar/LICENSE
- tar/go.mod
- tar/go.sum
- tar/tar.go
- tar/tar_opts.go
- tar/tar_test.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/tar_fuzzer.go
- Add new tar package to make Untar more extensible/testable.
- Set default `maxUntarSize` to `100Mb`.
- Tests core scenarios around `tar.Untar` usage.
- Removes `summary` as this is not used across Flux2.
This PR is to be follow-up by another that either deprecates the use of `untar` or redirects `untar.Untar` to the new pkg.
> Add tar.WithMaxUntarSize

- git/options.go
- git/options_test.go
Fallback to 'git' for username only when cloning Git repos through SSH,
since using 'git' as the username when cloning Git repos through HTTP(S)
might lead to 401s.
> git: fallback to 'git' for username only for ssh

- .github/workflows/build.yaml
Use the inbuilt cache feature in `actions/setup-go` which internally uses `actions/cache` itself.
This lets us cache module dependencies and previous builds as well which speeds up the entire workflow considerably from [~24 mins](https://github.com/fluxcd/pkg/runs/8111769892?check_suite_focus=true) to [~8mins](https://github.com/fluxcd/pkg/runs/8114612137?check_suite_focus=true) on Ubuntu.
It also fixes an issue where the cache was not being used on macOS runners: https://github.com/fluxcd/pkg/runs/8111770057?check_suite_focus=true#step:3:8
> ci: use inbuilt cache feature of setup-go

- git/gogit/go.mod
- git/internal/e2e/go.mod
- git/libgit2/go.mod
1. Bump pkg/git to v0.6.1 in pkg/git/gogit, pkg/git/libgit2 &
pkg/git/internal/e2e
2. Bump pkg/gittestserver to v0.7.0 in pkg/git/gogit, pkg/git/libgit2
& pkg/git/internal/e2e
> bump deps in git sub packages

- git/libgit2/go.mod
- git/libgit2/utils.go
Use UUID for transport options URL, decreasing the chance of a clash and
hence use of the wrong transport options for a Git operation.
> git/libgit2: use uuid for transport options usage 

- tar/tar_test.go
An helper func calling t.Errorf is being replaced by upstream with testingtypes.Errorf, which breaks the build. For the time being the helper func is being deleted.
> fuzz: Fix build

- oci/client/login.go
- oci/client/login_test.go
Hi 👋 
This can be re-used by flux to auto-login during artifacts operations as showcased in https://github.com/fluxcd/flux2/pull/3079
Let me know if you have any input!
Signed-off-by: Adrien Fillon <adrien.fillon@manomano.com>
> Add login capabilities to the OCI client

- git/libgit2/hack/install-libraries.sh
Cosign 1.12.0 comes with a breaking change where verify blob requires COSIGN_EXPERIMENTAL=1
Ref: https://github.com/fluxcd/source-controller/issues/899
> fix libgit2 build by enabling COSIGN_EXPERIMENTAL

- .github/workflows/e2e.yaml
Fixes the conditional logic to run GitHub E2E tests in CI barring PRs from forks
> ci: fix e2e conditonal logic

- oci/auth/aws/auth.go
- oci/auth/aws/auth_test.go
- oci/auth/login/login.go
- oci/auth/login/login_test.go
This change adds a new regex to parse AWS ECR OCI URLs when to allow URLs that point to the root of an AWS account's ECR registry, instead of forcing all repositories to contain a "/" character.
When accepted this will resolve https://github.com/fluxcd/source-controller/issues/905.
I've verified this change resolves the issue by rebuilding the source-controller image and deploying it to a Kubernetes cluster and verifying it can properly authenticate and pull from AWS ECR when given a URL like `oci://<account>.dkr.ecr.<region>.amazonaws.com` in a HelmRepository object.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203048932854531
> Add regex to support ECR as OCI Helm registry

- git/internal/e2e/go.mod
- git/internal/e2e/go.sum
- git/libgit2/clone.go
- git/libgit2/clone_test.go
- git/libgit2/go.mod
- git/libgit2/go.sum
- git/libgit2/internal/test/utils.go
- git/libgit2/libgit2-vars.env
- git/libgit2/repository_client.go
- git/libgit2/repository_client_test.go
- git/libgit2/transport/http.go
- git/libgit2/transport/http_test.go
- git/libgit2/transport/options.go
- git/libgit2/transport/ssh.go
- git/libgit2/transport/ssh_test.go
- git/libgit2/utils.go
The new version uses libgit2 1.5.0 and requires git2go/v34.
> build: Bump golang-with-libgit2 to v0.4.0

- runtime/conditions/testdata/crds/fake.toolkit.fluxcd.io_fakes.yaml
- runtime/conditions/testdata/fake.go
- runtime/object/doc.go
- runtime/object/object.go
- runtime/object/object_test.go
- runtime/reconcile/doc.go
- runtime/reconcile/result.go
- runtime/reconcile/result_test.go
Add runtime packages `reconcile` and `object`. `reconcile` package provides helpers for finalizing the result of reconciliation and create patch helper options based on the finalized results. `object` package provides helpers for reading and writing attributes of GitOps Toolkit objects (runtime.Object) without converting them to their actual types. This is used by `reconcile` while analyzing the results of reconciliation.
In source-controller, `internal/reconcile` package provides helpers for summarizing the result of reconciliation and patching the mutated object at the end. It helps ensure that the status of the object is kstatus compliant and also takes into consideration other status attributes like `status.lastHandledReconcileAt`. It also handles logging and event recording the …
> runtime: Add reconcile result finalizer

- oci/auth/aws/auth.go
- oci/auth/azure/auth.go
- oci/auth/gcp/auth.go
OCI autologin/contextual login in source-controller has per object cloud provider option in the spec. Image-reflector-controller v1beta2 API ([upcoming](https://github.com/fluxcd/image-reflector-controller/pull/311)) also configures it per object in the spec. The autologin flag log can be removed now.
> oci/auth: Remove log message about autologin flag

- oci/client/build_test.go
- oci/client/pull.go
- oci/go.mod
- oci/go.sum
- tar/tar.go
- untar/go.mod
- untar/go.sum
- untar/untar.go
The previous untar logic would take into memory each tar file entry,
causing large files to increase the likelihood of concurrent
reconciliations to cause OOM.
This change forces the untar process to use a buffer when processing
tar file entries, causing the memory profile per operation to be
reduced. On benchmarks below, the memory consumption per operation
was reduced from 10mb to 0.24mb:
```
Benchmark_Untar-16        6  188662186 ns/op  10962682 B/op  19836 allocs/op
Benchmark_Untar_Limit-16  8  131385484 ns/op   1964667 B/op  19274 allocs/op
```
The biggest file within the tar file was 95mb in size.
Testing the changes on `kustomize-controller` by tracking memory consumption, the instances with the new changes (blue and green) peak at 29mb whilst the existing code (yellow) peaks at …
> tar: Optimise memory usage

- runtime/patch/serial.go
- runtime/patch/serial_test.go
SerialPatcher is a wrapper around the patch helper to help perform consecutive patching of object in a transparent manner without the need to keep track of the object state after patching.
The SerialPatcher persists a before state of the object and a kubernetes client. The patch operation configurations aren't persisted and are accepted as argument to SerialPatcher.Patch(). This makes the patcher reusable in different scenarios during its lifetime.
> runtime/patch: Add SerialPatcher

- oci/client/diff.go
- oci/client/diff_test.go
**_Contributor details_**:
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
**_Features that are included in the PR_**:
/cc @stefanprodan
> oci: Use upstream layer digest for artifact diff

- git/gogit/fs/osfs_os.go
- git/gogit/fs/osfs_test.go
Go-git expects that the dir containing the target symlink exists, which is the same behaviour observed for regular files. Regular files and dir are managed by `fs.OpenFile()`, which is call by both `fs.Open()` and `fs.Create()`.
With the this change, `fs.Symlink()` aligns with the behaviour elsewhere within go-git.
> gogit: create parent dirs for fs.Symlink()

- git/gogit/repository_client.go
- git/gogit/repository_client_test.go
Force push enables use cases in image automation controller in which a branch has changed in-between a Clone and the push operation. An example would be long-lived push branches that become stale from the default or clone branch.
Relates to: https://github.com/fluxcd/image-automation-controller/issues/450
Expands on: https://github.com/fluxcd/image-automation-controller/pull/451
> gogit: Add WithForcePush

- git/gogit/transport.go
- git/gogit/transport_test.go
Some applications like CLIs might prefer to use the known_hosts of the machine which then leads to an empty known_hosts value being used in `git.AuthOptions` resulting in an invalid callback.
> git/gogit: configure hostkey callback only when known_hosts is provided

- git/client.go
- git/gogit/clone.go
- git/gogit/clone_test.go
- git/libgit2/clone.go
Add support for cloning empty repos using `go-git` and `libgit2`.
`go-git` returns an error when cloning an empty repository directly, which is handled by using the advice provided here: https://github.com/go-git/go-git/issues/118#issuecomment-773488577. `libgit2` doesn't return an error and thus the change is much simpler.
The `go-git` package gets test coverage for this scenario but the `libgit2` package does not because of the following weird behavior:
```go
_, err := git2go.InitRepository(filepath.Join(server.Root(), emptyRepoPath), true)
err = l.remote.Fetch([]string{branch},
&git2go.FetchOptions{
DownloadTags:    git2go.DownloadTagsNone,
RemoteCallbacks: remoteCallBacks,
},
"")
if err != nil {
return nil, fmt.Errorf("unable to fetch remote '%s': %w", url, gitutil.LibGit2Error(err)) …
```
> git: add support for cloning empty repos

- git/gogit/clone_test.go
- git/gogit/repository_client.go
- git/libgit2/clone_test.go
- git/libgit2/repository_client.go
Blocks the transmission of credentials over HTTP by default but add a new `WithInsecureCredentialsOverHTTP` which allows consumers to re-enable it.
Passing credentials in plain-text over HTTP is not recommended for production environments.
> git: Add new WithInsecureCredentialsOverHTTP

- git/internal/e2e/gitkit_test.go
- git/internal/e2e/gitlab_ce_test.go
The two sets of [tests affected](https://github.com/fluxcd/pkg/actions/runs/3438702214) are only executed at main branch and were sending credentials over HTTP, which has been blocked by #396. The changes use WithInsecureCredentialsOverHTTP to enable such behaviour.
> build: Fix gitkit and gitlab tests

- .github/workflows/actions.yaml
- .github/workflows/build.yaml
- .github/workflows/cifuzz.yaml
- .github/workflows/e2e.yaml
- .github/workflows/ossf.yaml
- .github/workflows/scan.yaml
- git/internal/e2e/git_utils.go
- git/internal/e2e/github_test.go
- git/internal/e2e/gitkit_test.go
- git/internal/e2e/gitlab_ce_test.go
- git/internal/e2e/gitlab_test.go
Refactored the e2e tests so Git client logic is shared across all tests.
Node.js 12 actions are deprecated so moving the actions to the latest version to remove warnings whilst running CI builds.
> build: Refactor e2e tests and update GitHub actions

- apis/meta/conditions.go
This PRs adds the following reasons to the `fluxcd/pkg/apis/meta` package:
- ProgressingWithRetry
- DependencyNotReady
- InvalidPath
- InvalidURL
- InsecureConnectionsDisallowed ([RFC-0004](https://github.com/fluxcd/flux2/tree/main/rfcs/0004-insecure-http))
- UnsupportedConnectionType ([RFC-0004](https://github.com/fluxcd/flux2/tree/main/rfcs/0004-insecure-http))
> apis/meta: Add common failure reasons

- tests/fuzz/oss_fuzz_build.sh
Temporarily ignores `recorder_fuzzer_test.go`.
> build: Fix fuzz tests

- runtime/conditions/patch_fuzz_test.go
- runtime/conditions/patch_test.go
- runtime/conditions/unstructured_fuzz_test.go
- runtime/conditions/unstructured_test.go
- runtime/events/recorder_fuzzer_test.go
- tests/fuzz/README.md
- tests/fuzz/oss_fuzz_build.sh
Establish conventions which aligns with what is supported upstream today, whilst expanding on documentation to ensure other contributors have pointers on how to debug/check for issues going forwards.
These changes ensures all fuzz tests are executed (xref #415).
> build: Improve fuzz tests' reliability

- git/gogit/fs/osfs_os.go
- git/gogit/fs/osfs_test.go
Modify `Chroot()` into returning a new OS filesystem. The filesystem returned is not actually chrooted, but only enforces all files to be under the root working directory. This is required to avoid breaking cloning repos with submodules. Ref: https://github.com/fluxcd/go-git/blob/d979ddd67ae30aebcdd285c0b0133594e7194980/storage/filesystem/dotgit/dotgit.go#L1100-L1103
Related to: https://github.com/fluxcd/source-controller/issues/970
> git/gogit: modify chroot to return a new os filesystem

- kustomize/kustomize_generator.go
- kustomize/kustomize_generator_test.go
- kustomize/testdata/components/kustomization.yaml
Ref: fluxcd/kustomize-controller#753
Signed-off-by: Kristian Klausen <kristian@klausen.dk>
> Add support for Kustomize components

- git/gogit/client.go
- git/gogit/client_test.go
- git/gogit/clone.go
- git/gogit/transport.go
- git/gogit/transport_test.go
Add a new `AuthMethod` which uses the default `known_hosts`. Fallback to this when the provided auth options has an empty private key and known hosts.
Related to: https://github.com/fluxcd/flux2/issues/3358
> git/gogit: fallback to machine known_hosts

- git/gogit/go.mod
Fixes wrong version for gittestserver introduced by 49c90f601a5161a009735f72b006bbe8e1531d3d.
> git/gogit: bump to gittestserver v0.8.0

- git/internal/e2e/go.mod
- git/libgit2/go.mod
Fixes wrong version for git/gogit introduced by https://github.com/fluxcd/pkg/commit/51f482bd11c2327ea6dee81230ab21ecd46ec7b9
> git/{libgit2,e2e}: bump git/gogit to v0.3.1

- git/gogit/clone_test.go
- git/gogit/fs/osfs_os.go
- git/gogit/fs/osfs_test.go
- git/gogit/go.mod
- git/testdata/git/repo2/bar.txt
Use `filepath-securejoin` to join root working dir of the base filesystem and the desired chroot root and return a filesystem using the resulting path as the root working dir. Add a test which clones a repo with a submodule to make sure this doesn't get broken again.
Related to: https://github.com/fluxcd/source-controller/issues/970
> git/gogit: fix chroot filesystem and add submodule test

- git/gogit/client.go
- git/gogit/client_test.go
- git/gogit/clone.go
At present go-git does not support the `MULTI_ACK` capability, which means that follow-up fetches on a given remote will fail.
To support Image Automation Controller use cases, the SwitchBranch was initially short-circuited to avoid additional fetches. However, this has the side effect of the controller pushing the same change to the target repository multiple times. (fluxcd/flux2#3384)
In order to avoid this, a new `WithSingleBranch` option was created to enable the download of all references at the initial clone. From now on `SwitchBranch` has the single responsibility of switching branches, and no longer pulling references.
The package `git/gogit`'s primary goal is to support Flux use cases, currently there is no need to expand the current API to expose ways for users to refresh …
> gogit: Add WithSingleBranch

- ssa/manager_apply.go
- ssa/manager_apply_test.go
If an object was created but then marked as ignored in source, we should skip applying it even if the in-cluster object has no ignore annotation/label.
> ssa: Ignore objects even if they exist in cluster

- runtime/client/client.go
In `client-go` version `v0.25.0` the burst limit was increased to 300 for the discovery client: https://github.com/kubernetes/kubernetes/pull/109141
This is especially useful for clusters with `crossplane` ([see](https://github.com/crossplane/crossplane/issues/3272)), but since `client-go` itself got the change as well, I think it makes sense to increase the default for Flux controllers too, because - if I am not mistaken - this setting goes down into the discovery client, e.g. for `helm-controller`:
1. https://github.com/fluxcd/helm-controller/blob/v0.29.0/go.mod#L24
2. https://github.com/fluxcd/helm-controller/blob/v0.29.0/go.mod#L13
3. https://github.com/fluxcd/pkg/blob/runtime/v0.27.0/runtime/client/client.go#L59-L65
4. https://github.com/fluxcd/helm-controller/blob/v0.29.0/internal/ku …
> Increase default burst to 300 to conform `client-go`

- git/gogit/client.go
- git/gogit/clone.go
- git/gogit/clone_test.go
- git/libgit2/client.go
- git/repository/options.go
Add a new checkout strategy that enables checking out to a Git reference: https://git-scm.com/book/en/v2/Git-Internals-Git-References. This enables users to check out to a raw reference (that doesn't necessarily point to a branch/tag).
Related to: https://github.com/fluxcd/source-controller/issues/1017
> add support for checking out git repo to a ref

- sourceignore/go.mod
- sourceignore/go.sum
- ssa/changeset.go
- ssa/manager.go
- ssa/manager_apply_test.go
- ssa/manager_delete_test.go
- ssa/manager_diff_test.go
This makes the Action type a first-class citizen, over casting it to a string. Resolving a whole lot of annoyances while working with the change set when determining if something equals to (the string representation of).
> ssa: make `Action` true to type

- .github/workflows/build.yaml
- CONTRIBUTING.md
- Makefile
This is much cheaper than running all `test-%` variants, which can now be triggered using `make test`.
It wil also help speeding up the extremely slow CodeQL workflow, which at present runs the whole test suite without it being strictly required. Due to the behavior of the Autobuild step described in https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#go
> Change `all` target to run only `tidy|generate|fmt|vet`

- ssa/changeset.go
- ssa/manager_apply.go
- ssa/manager_apply_test.go
- ssa/manager_delete.go
- ssa/manager_delete_test.go
Instead of reporting `unchanged` for objects which have the reconciliation disabled, we now mark these objects as `skipped`. 
Ref: https://github.com/fluxcd/kustomize-controller/issues/794
> ssa: Add `skipped` action to report ignored resources

- git/git.go
- git/git_test.go
- git/gogit/clone.go
- git/gogit/clone_test.go
- git/utils_test.go
Add a new method `AbsoluteReference()` to show the full reference along
with the hash of a commit object. Refactor logic related to
`LastObservedCommit` in order for it to work with full references when
required.
Fixes: #476
> git: add support for showing full references

- runtime/events/recorder.go
This commit changes the log level of the event recorder to `trace`, reduing the noise one may receive while running a controller with log level set to `debug` (to get a more extensive insight into what a controller reports, but not as in-depth as `trace`).
This seems a more appropriate level, given the controller often emits a variation of the information pushed in an event by itself on log level `info`, and the knowledge about emitted events likely only has value when deeply looking into the behavior of the application.
> runtime/events: change log level to trace

- oci/client/meta.go
- oci/client/push_pull_test.go
This feature will enable us to make the Flux artifacts conform to ArtifactHub which requires extra annotations for advertising the artifact license, documentation, etc.
> oci: Allow setting custom annotations on artifacts

- runtime/logger/logger.go
This adds a new helper which simultaneously configures controller-runtime and klog to make use of the same logger instance.
> runtime/logger: add `SetLogger` helper

- runtime/metrics/recorder.go
We encountered a delay in reconciliation which end up taking to more than 15 minutes. The current histogram metrics configuration doesn't help us to see the actual value.
This change will set the minimum range from 1nanoseconds, to 1millisecond. This is assuming 1 millisecond is blazingly fast that we don't care anything beyond that.
It'll also change the maximum range from 10s, to 1 hour. It's assuming 1 hour is terribly slow, and we don't care anything beyond that.
Ideally, this configuration should be configurable by user, as each company have their own preferences.
> Change the metric bucket into a more useful range.

- oci/go.mod
- oci/go.sum
- oci/tests/integration/go.mod
- oci/tests/integration/go.sum
https://pkg.go.dev/vuln/GO-2023-1631
> oci: update google.golang.org/protobuf to v1.29.1

- runtime/patch/suite_test.go
Once in awhile the tests appear to fail on this because it appears to take a little longer than the current configurations. Slightly increase both, to hopefully deal with it for good.
- https://github.com/fluxcd/pkg/actions/runs/4530985720/jobs/7980583099
- https://github.com/fluxcd/pkg/actions/runs/4500139007/jobs/7918873957
- https://github.com/fluxcd/pkg/actions/runs/4500711383/jobs/7920192543
> runtime/patch: increase (extended) timeout tests

- runtime/controller/watch.go
- runtime/controller/watch_test.go
Add `--watch-label-selector` flag to controller runtime. When specified the controller's reconcilers will only watch for changes of those resources with matching labels.
To restrict the controller watch, the selector exposed by this package must be wired in each controller's cache manager.
This enables horizontal scaling of Flux controllers, where each controller can be deployed multiple times with a unique label selector which is used as the sharding key.
For example, to shard the reconciliation of HelmReleases in a cluster, user will deploy two extra helm-controller instances:
- Deployment/helm-controller with `--watch-label-selector=sharding.fluxcd.io/shard notin (shard1, shard2)` 
- Deployment/helm-controller-1 with `--watch-label-selector=sharding.fluxcd.io/shard=shard1` 
- …
> runtime: Add controller sharding capability based on label selector

- oci/client/client.go
Allow consumers to inspect the crane options used by the OCI client.
> oci: Add `GetOptions` to client

- apis/event/v1beta1/metadata.go
Part of the PRs for https://github.com/fluxcd/helm-controller/issues/678 alongside https://github.com/fluxcd/helm-controller/pull/681 and https://github.com/fluxcd/notification-controller/pull/518
> Add metadata key for holding an arbitrary identification token

- http/fetch/archive_fetcher.go
- http/fetch/archive_fetcher_test.go
Would have helped with  https://github.com/fluxcd/flux2/issues/3861.
> http/fetch: improve error messages

- oci/client/build_test.go
- oci/client/client.go
- oci/client/delete_test.go
- oci/client/diff_test.go
- oci/client/list_test.go
- oci/client/login_test.go
- oci/client/push_pull_test.go
- oci/client/tag_test.go
Part of: https://github.com/fluxcd/flux2/issues/3714
This pull request adds a function to configure the retry backoff on [crane](https://github.com/google/go-containerregistry/tree/main/pkg/crane) option for different OCI operations.
It also removes the `NewLocalClient` function, adding a function `DefaultOptions` that returns an array of crane.Options that can be passed into `NewClient` to get the same result.
> oci/client: Configureable retry backoff

- git/gogit/client.go
- git/gogit/client_test.go
- git/gogit/clone.go
- git/gogit/clone_test.go
- git/gogit/internal/test/http_proxy_test.go
- git/gogit/internal/test/socks_proxy_test.go
- git/internal/e2e/utils.go
- git/repository/client.go
- git/repository/options.go
Add `PushConfig` for configuring a push operation. Users can use `PushConfig.Refspecs` to specify the refspecs when using `Push()`.
Furthermore, fix a bug related to `Push()` where all refs were pushed to origin, since we did not specify a refspec and the default refspec used by gogit is `refs/heads/*:/refs/heads/*`.
Add `PushConfig.Force` for force pushing and remove `gogit.Client.forcePush` in favor of the former.
Remove some stale test cases from `TestSwitchBranch` related to force push since we don't check if force pushing is enabled while switching branches anymore. Ref: https://github.com/fluxcd/pkg/pull/433
Part of: https://github.com/fluxcd/image-automation-controller/issues/509
> git: add `PushConfig` to specify push config and add support for refspecs

- git/gogit/transport.go
- git/gogit/transport_test.go
Set `HostKeyCallback` for the parent `PublicKeys` object to avoid setting the callback to one that uses the system's known_hosts.
Fixes errors seen in: https://github.com/fluxcd/source-controller/actions/runs/5072863613/jobs/9111130473#step:4:164
> git/gogit: set `HostKeyCallback` for parent `PublicKeys` object

- oci/client/login.go
- oci/client/retry_transport.go
This pull request is a follow-up to https://github.com/fluxcd/pkg/pull/533
It adds a function `WithRetryTransport` that accepts a remote.Backoff and returns a crane.Option that sets a transport which uses the backoff when retrying operations. This needed because the `remote.WithRetryBackoff(backoff)` is not used for retrying transport operations. For more context see: https://github.com/google/go-containerregistry/issues/1692
> [oci] Add function for configuring transport with retry backoff

- git/gogit/client.go
- git/gogit/clone.go
- git/gogit/clone_test.go
- git/gogit/go.mod
- git/internal/e2e/go.mod
- git/internal/e2e/go.sum
Add `WithProxy()`, a `ClientOption` which configures the proxy settings for a `gogit.Client`. All remote operations performed by the client will then use the configured proxy.
Atm, the only way to use a proxy is to use the standard env vars, `HTTP_PROXY`, `HTTPS_PROXY`, etc. The problem with this is that its configuration at a global level, i.e. all clients will be forced to use these proxy settings. This PR allows for using different proxy settings for different clients, which is particularly helpful when working in multi tenant environments.
> git/gogit: Add support for per client proxying

- git/gogit/client.go
Remove `multi_ack` and `multi_ack_detailed` from `transport.UnsupportedCapabilities` as they're required to work Git v2 servers such as Azure Devops and AWS CodeCommit.
Related to fluxcd/flux2#3936
> git/gogit: add multi_ack/multi_ack_detailed as a supported capability

- git/gogit/client.go
go-git returns an unhelpful error message `unknown error: remote:` when trying to push to a GitLab repository using a deploy key that does not have push access. Translate the error message to something more helpful and informative.
Related to: https://github.com/fluxcd/image-automation-controller/issues/491
> git/gogit: Translate misleading go-git write access error of Gitlab

- runtime/controller/connection.go
Add a generic flag `--insecure-allow-http` to allow users to enable the use of plain HTTP connections.
Related to: https://github.com/fluxcd/flux2/issues/3310
> runtime/controller: Add generic flag for allowing insecure HTTP connections

- oci/client/push.go
- oci/client/push_pull_test.go
For reproducible builds we need to allow consumers to set their own created date instead of enforcing time.now.
> oci: Allow consumers to set the OCI artifact created date

- ssa/manager_apply.go
Part of fix for: https://github.com/fluxcd/flux2/issues/3334
This pull request continues on to apply for NotFound errors on object deletion.
This helps in cases where we have previously deleted the object but due to some reason the `getError`(slow API server?) returns another other than not found even though the object no longer exists
> ssa apply: check for NotFound errors on Delete

- runtime/controller/connection.go
- runtime/go.mod
Add `CheckEnvironmentCompatibility()` to check whether the configured connection options are compatible with the environment, by checking env vars like `HTTP_PROXY` and `HTTPS_PROXY`.
> runtime/client: add util func to check conn options compatibility with env

- oci/auth/aws/auth.go
- oci/auth/aws/auth_test.go
- oci/auth/login/login.go
- oci/go.mod
This pull request basically reverts a change introduced in #560  where the region of the instance was used instead of the region from the registry url
Ref: https://github.com/fluxcd/source-controller/issues/1155
> Use registry region to get token for AWS

- ssa/manager_apply_test.go
- ssa/testdata/test2.yaml
Prove that https://github.com/fluxcd/kustomize-controller/issues/923 is fixed in Flux v2.0.0
Closes: https://github.com/fluxcd/kustomize-controller/issues/923
> ssa: Add test for duplicate ports different proto

- ssa/go.mod
- ssa/go.sum
- ssa/manager_apply.go
- ssa/manager_delete_test.go
- ssa/manager_wait.go
- ssa/manager_wait_test.go
- ssa/testdata/test10.yaml
This pull request adds a FailFast option to the `WaitOptions` in the ssa pkg. When this option is set, the Wait function returns early if there are stalled resources.
Ref: https://github.com/fluxcd/flux2/discussions/3980
Ref: https://github.com/fluxcd/kustomize-controller/issues/701
> Add failfast option to ssa.Wait

- ssa/utils.go
- ssa/utils_test.go
Custom admission webhooks such as those used by Google Cloud and Kubernetes CEL which reject requests due to immutable field changes do not comply with `errors.IsInvalid`. For Flux to be able to force apply resources rejected by these controllers, we have to do a match on the error string and look for `is immutable`.
Ref:
- https://github.com/fluxcd/kustomize-controller/issues/834
- https://github.com/stefanprodan/timoni/issues/153
> ssa: Detect immutable errors from CEL and custom webhooks

- runtime/jitter/interval.go
- runtime/jitter/interval_test.go
- runtime/jitter/jitter.go
- runtime/jitter/jitter_test.go
This adds a `jitter` package to runtime to allow the configuration of a random +/-% jitter to the interval at which resources are requeued.
Applying jitter to the interval duration can be useful to mitigate spikes in memory and CPU usage caused by many resources being configured with the same interval.
> runtime: add `jitter` utils and options

- git/internal/e2e/utils.go
- oci/client/suite_test.go
- oci/tests/integration/suite_test.go
Ref: https://go.dev/doc/go1.20#math/rand
> *: remove deprecated `rand.Seed` calls

- helmtestserver/go.mod
- helmtestserver/go.sum
- github.com/docker/docker to v23.0.3 to mitigate warning on CVE-2023-28840, CVE-2023-28841 and CVE-2023-28842
> helmtestserver: update dependencies

- runtime/jitter/interval.go
This is a more friendly default for higher interval values (e.g. `1h`), which would otherwise result in a 12-minute time-window.
> runtime/jitter: change default to +/-5%

- ssa/manager_apply.go
- ssa/manager_apply_test.go
- ssa/utils.go
Add `IfNotPresentSelector` to the apply options, the resources that match this selector will be applied on the cluster only if they don't exist.
Ref: https://github.com/fluxcd/kustomize-controller/issues/936
> ssa: Add `IfNotPresent` apply strategy

- git/gogit/client.go
- git/repository/options.go
Add `PushConfig.Options` to allow specifying the push options to use when performing a push operation. For details about push options, please see: https://git-scm.com/docs/git-push#Documentation/git-push.txt---push-optionltoptiongt
This is useful for platforms like GitLab when used with image-automation-controller by enabling the creation of MRs automatically upon a push operation (ref: https://docs.gitlab.com/ee/user/project/push_options.html#push-options-for-merge-requests)
Update: Wrote a test case to test whether the push options are indeed send to the Git server.
```go
func TestPush_options(t *testing.T) {
g := NewWithT(t)
ggc, err := NewClient(t.TempDir(), &git.AuthOptions{
Transport: git.HTTPS,
Username:  "aryan9600",
Password:  "***",
})
g.Expect(err).ToNot(HaveOccurred())
_, err …
```
> git: add support for push options

- git/options.go
- git/options_test.go
Add support for key `ca.crt` in `NewAuthOptions()` to read CA certificate data. It takes precedence over `caFile`.
> git: add support for key `ca.crt` to specify CA data

- oci/auth/azure/auth.go
- oci/auth/azure/auth_test.go
When using the OCI authentication in azure with managed identity in usgovernment  environment, the source-controller  cannot get the permissions for the cloud because it defaults to the public azure cloud. 
```
error logging into ACR error exchanging token: unexpected status code 401 from exchange request,
response body: {\"errors\":[{\"code\":\"UNAUTHORIZED\", \"message\":\"retrieving permissions failed: 
https://management.usgovcloudapi.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerRegistry/registries/xxx/providers/Microsoft.Authorization/permissions/?api-version=xxx\"}]}"
```
The fix proposes a map for each azure cloud environment that is automatically detected by the suffix of the ACR.
> oci/auth: Add support for Azure China and US Gov regions

- git/git.go
- git/git_test.go
- git/gogit/clone.go
- git/gogit/clone_test.go
Add a new struct `Tag` that represents a Git annotated tag and add it as a new field `Commit.ReferencingTag`, allowing for a commit to contain information about its referencing tag. Add support for verifying the referencing tag as well.
Update the cloning logic to include the tag object in the returned commit object when checking out via a specific tag, a semver range or if the provided refname points to a tag.
Related to: https://github.com/fluxcd/source-controller/issues/1133
Example usage: https://github.com/fluxcd/source-controller/pull/1187
> git: Add support for adding tag info to commit

- ssa/manager_apply_test.go
- ssa/manager_diff.go
This pull request removes the special error handling for secrets that was used to prevent leaking secret data in the error message. With the move to server-side apply, the original patch (which contained the secret data) is no longer returned in the error.
Fix: https://github.com/fluxcd/kustomize-controller/issues/946
Fix: https://github.com/fluxcd/flux2/issues/4122
> Remove special error handling for secrets

- .github/workflows/e2e.yaml
The bot doesn't have access to the secrets needed to perform these tests.
> Skip git e2e tests for dependabot PRs

- oci/auth/aws/auth.go
- oci/auth/azure/auth.go
- oci/auth/flag_test.go
- oci/auth/gcp/auth.go
- oci/auth/login/login.go
This helps avoid importing the controller-runtime pkg/client/config package which has a [flag initialization](https://github.com/kubernetes-sigs/controller-runtime/blob/2a553d6f910dfc4b0796142ba1e059639a21c54a/pkg/client/config/config.go#L44) for "kubeconfig". This results in all the users of the oci package to also have the flag initialized in their applications. The root level controller-runtime package has type aliases which we use a lot for ease of use, but the package also [imports the client config package](https://github.com/kubernetes-sigs/controller-runtime/blob/2a553d6f910dfc4b0796142ba1e059639a21c54a/alias.go#L23).
The usage of controller-runtime in oci package is just for logging. Importing the pkg/log package specifically helps avoid importing the client config which sets the …
> oci: Use controller-runtime pkg/log specifically

- http/fetch/archive_fetcher.go
- http/fetch/go.mod
- http/fetch/go.sum
- oci/client/pull.go
- oci/go.mod
- oci/go.sum
- tar/go.mod
- tar/go.sum
- tar/symlink_test.go
- tar/tar.go
- tar/tar_opts.go
This is a followup of https://github.com/fluxcd/pkg/pull/653 as pulling any OCI artifact currently fails if it contains symlinks.
Changes:
- Add `WithSkipSymlinks` option to `tar.Untar`
- Add test to prove that tarballs with symlinks no longer error out during decompression if skip is enabled
- Use `WithSkipSymlinks` in `oci/client.Pull` so that the Flux CLI will not error out if it finds symlinks in the tarball, and instead it will skip them
- Use `WithSkipSymlinks` in `http/ArchiveFetcher.Fetch` to avoid failing to extract artifacts which are not recompiled by source-controller
Ref: https://github.com/fluxcd/pkg/issues/538
> Skip symlinks during OCI layer decompression

- ssa/utils.go
Add match variant to capture immutable field behaviour of https://github.com/GoogleCloudPlatform/k8s-config-connector
> ssa: Extend CEL immutable error detection

- ssa/manager_diff.go
- ssa/sanitize.go
- ssa/sanitize_test.go
- ssa/utils.go
- ssa/utils_test.go
Instead of masking the data with `****` or `*****`, provide an easier to distinguish `*** (before)` and `*** (after)` for values which have changed. Matching the output of `kubectl diff`.
In addition, make the function public as it can be of use outside of the `Diff` of the resource manager, and allow passing only one instance of an object (for scenarios where a resource is either created or deleted).
> ssa: improve data masking

- ssa/manager_apply.go
Set the delete propagation to background to cleanup the pods for recreated Kubernetes Job.
Fix for `child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning`. Because we haven't explicitly set the propagation policy, etcd gets filled will orphan pods after each force apply.
> ssa: Set force delete propagation to cleanup jobs

- ssa/go.mod
- ssa/go.sum
- ssa/jsondiff/diff.go
- ssa/jsondiff/mask.go
- ssa/jsondiff/mask_test.go
- ssa/jsondiff/options.go
- ssa/jsondiff/patch.go
- ssa/jsondiff/selector.go
- ssa/jsondiff/selector_test.go
- ssa/jsondiff/suite_test.go
- ssa/jsondiff/testdata/deployment.yaml
- ssa/jsondiff/testdata/empty-configmap.yaml
- ssa/jsondiff/testdata/empty-secret.yaml
- ssa/jsondiff/testdata/service.yaml
- ssa/jsondiff/unstructured.go
- ssa/jsondiff/unstructured_test.go
> ssa: introduce `jsondiff` package

- oci/tests/integration/suite_test.go
Explicitly set the test program exit code to 1 when terraform destroy fails to delete the infrastructure.
This was observed when GKE clusters failed to delete due to delete protection enabled by default in the latest version of terraform provider google.
Verified locally by reproducing the GKE delete failure:
```console
module.gcr.google_artifact_registry_repository.this: Destroying... [id=projects/test-project/locations/us-central1/repositories/flux-test-sharing-sawfly]
module.gke.google_container_cluster.primary: Destroying... [id=projects/test-project/locations/us-central1/clusters/flux-test-sharing-sawfly]
module.gcr.google_artifact_registry_repository.this: Destruction complete after 3s
Error: Cannot destroy cluster because deletion_protection is set to true. Set it to false to …
```
> oci/tests/int: Set exit code 1 on tf destroy fail

- oci/client/build.go
- oci/client/build_test.go
- oci/client/diff.go
- oci/client/diff_test.go
- oci/client/pull_test.go
- oci/client/push.go
- oci/client/push_pull_test.go
- oci/globals.go
This pull request adds different layer types when pushing an OCI image. The default is the `tarball` where the layer contains a tarball created from the sourcePath. The `static` type creates a layer containing the uncompressed contents of the file.
It also adds an option for configuring the media type extension of the layer and reactors the Push methods with functional options.
> [oci] Extend oci.Push to create layer with static uncompressed contents

- ssa/manager_apply.go
- ssa/manager_delete.go
- ssa/manager_diff.go
When attempting to retrieve the object, setting the GVK on the Unstructured is sufficient to be able to retrieve it from the cluster.
This avoids deep-copying the object in full and then `nil` writing it again when it does not exist in the cluster. Which can potentially save quite some duplicate data when e.g. dealing with Custom Resource Definitions or other large object kinds.
> ssa: prevent unnecessary `DeepCopy`

- git/gogit/go.mod
- git/internal/e2e/go.mod
- kustomize/go.mod
- oci/go.mod
> Update internal dependencies

- http/fetch/archive_fetcher.go
- http/fetch/go.mod
- http/fetch/go.sum
- http/fetch/logger.go
This allows for the configuration of a logger on the retryable HTTP client. While adding builtin support for providing a `logr.Logger` instance, which will be wrapped in  a `retryablehttp.LeveledLogger` to only log errors.
Part of: https://github.com/fluxcd/flux2/issues/4472
> http/fetch: allow configuring a logger on client

- runtime/conditions/setter.go
- runtime/conditions/setter_test.go
xref: https://github.com/fluxcd/flux2/issues/4470
> runtime: Trim the condition message to the max accepted length

- kustomize/filters.go
- kustomize/kustomize_generator_test.go
- kustomize/testdata/remote/configmap.yaml
- kustomize/testdata/remote/kustomization.yaml
Fix an issue where kustomizations with remote resources are silently dropped from `flux build ks`. The behavior change appears to have been introduced in https://github.com/fluxcd/flux2/pull/3763 and https://github.com/fluxcd/pkg/pull/528 when adding filters to ignore the source path. The behavior skips urls since they don't match file paths, but that had the side effect of not including them in the generated `Kustomization`. This PR reverts to the old behavor of ignoring remote urls and keeping them in the kustomization -- which is fine since source ignore paths are about paths in the source tree and not remote resources.
Fixes https://github.com/fluxcd/flux2/issues/4146 which describes how to reproduce the issue. An example test is included that exercises the issue ensuring the remote …
> Fix a silently dropping Kustomization remote resources

- ssa/errors/errors.go
- ssa/manager_apply_test.go
Fix regressing bug introduced in SSA refactoring.
Fix: #716
> ssa: Restore `namespace not specified` error handing

- ssa/manager_wait.go
- ssa/manager_wait_test.go
If the context deadline has not been reached, include only the failed resources in the returned error. This makes the health check error message concise, instead of listing potentially hundreds of resources in progress, we only list the ones that actually failed.   
Part of: https://github.com/fluxcd/flux2/issues/4556
Fixes: https://github.com/fluxcd/pkg/issues/715
Supersedes: https://github.com/fluxcd/pkg/pull/717
> ssa: Improve wait error reporting

- runtime/conditions/getter.go
- runtime/conditions/getter_test.go
Add `HasAnyReason` helper function that returns true if a condition with the given type exists and any of the given reasons exist.
To be used in: https://github.com/fluxcd/helm-controller/pull/884
> runtime: Add `HasAnyReason` to conditions getter

- runtime/conditions/testdata/fake.go
This tag isn't used by controller-tools, only `nonNamespaced` is.
Context: https://cloud-native.slack.com/archives/CLAJ40HV3/p1708794732147909
Tested by running `make generate` and verifying that there is no diff.
> Remove `genclient:Namespaced` tag

- .github/workflows/actions.yaml
- Makefile
- actions/envtest/action.yml
[This commit](https://github.com/kubernetes-sigs/controller-runtime/commit/4c2442e4d743d172a2e0126a841ecd274fffc228) causes failures to install envtest, see https://github.com/kubernetes-sigs/controller-runtime/issues/2720 for details.
This commit pins envtest to the latest version that still works.
> Pin envtest version

- actions/crdjsonschema/entrypoint.sh
- actions/crdjsonschema/openapi2jsonschema.py
This enables JSON schema extensions to validate Flux2 resources by pointing to the `all.json` file. Background: https://github.com/fluxcd-community/flux2-schemas/issues/23
I dropped some old Python2 compatibility code (`iteritems`) and I am using dataclasses (minimum Python version 3.7). I think this is not a problem because it is being run through the Dockerfile which is using `python:3-alpine` anyways.
When using the [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension you could use this new `all.json` schema like so (if this PR is merged and the flux2-schemas repo is updated):
**.vscode/settings.json**
```json
"yaml.schemas": {
"https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json": "*.yaml"
},
```
This would net you nice …
> crdjsonschema action now creates a `all.json` schema to validate any Flux2 resource via a single schema

- apis/meta/conditions.go
Adding "reason" constants to the pkg repo as suggested in this PR: https://github.com/fluxcd/notification-controller/pull/701
This will be followed by a PR in kustomize controller to refer to these constants from common pkg repo here and updates to the above mentioned PR to do the same.
> Adding common "reason" constants

- .github/workflows/e2e.yaml
We disable the bitbucket-server e2e tests until a new test environment is available.
This will fix #750
> Disable bitbucket-server e2e

- ssa/jsondiff/unstructured.go
- ssa/jsondiff/unstructured_test.go
We want to enable this behaviour for use cases where different controllers must coordinate in order to mutate a resource.
ref: https://github.com/fluxcd/helm-controller/issues/922
> Return a DiffTypeExclude when exclusion annotation is set in cluster

- kustomize/filters.go
- kustomize/kustomize_generator.go
- kustomize/kustomize_generator_test.go
- kustomize/testdata/noResources/ks.yaml
- kustomize/testdata/noResources/kustomization.yaml
Fix breaking change in Kustomize >=v5.2 where a kustomization.yaml with `resources: []` results in a build error.
Fix: https://github.com/fluxcd/flux2/issues/4601
> kustomize: Allow empty resources in `kustomization.yaml`

- envsubst/README.md
- envsubst/doc.go
- envsubst/eval.go
- envsubst/eval_test.go
- envsubst/funcs.go
- envsubst/funcs_test.go
- envsubst/go.mod
- envsubst/go.sum
- envsubst/parse/node.go
- envsubst/parse/parse.go
- envsubst/parse/parse_test.go
- envsubst/parse/scan.go
- envsubst/path/match.go
- envsubst/template.go
This PR contains a fork of https://github.com/gomodules/envsubst and incorporates https://github.com/drone/envsubst/pull/34.
This **permanent fork** is needed because envsubst powers a GA feature of Flux, and the Drone's project looks like is no longer maintained.
xref: https://github.com/fluxcd/flux2/issues/4694
> Add envsubst package

- kustomize/go.mod
- kustomize/go.sum
- kustomize/kustomize_varsub.go
- kustomize/kustomize_varsub_test.go
- kustomize/testdata/varsubstrict/config.yaml
- kustomize/testdata/varsubstrict/kustomization.yml
Ref: https://github.com/fluxcd/flux2/issues/4694
> kustomize: Implement envsubst strict mode

- kustomize/kustomize_generator.go
- kustomize/kustomize_generator_test.go
- kustomize/testdata/name/ks.yaml
- kustomize/testdata/name/kustomization.yaml
Part of: https://github.com/fluxcd/kustomize-controller/issues/1133
> kustomize: Add support for `namePrefix` and `nameSuffix`

- tar/tar.go
- tar/tar_opts.go
Alternatively I could just NOT error when Gzip header fails. The choice is up to you dear maintainers.
> feat: add un-taring plain, unzipped tar files

- oci/auth/login/login.go
- oci/auth/login/login_test.go
We currently use the full `image url` as key for the cache. The new change introduced here reduce cardinality and permit reusing a cached credentials based on `aws region`, `gcp project` and `azure endpoint`.
> Cache credentials tokens

- oci/auth/aws/auth.go
- oci/auth/azure/auth.go
- oci/auth/azure/exchanger.go
- oci/auth/azure/exchanger_test.go
- oci/auth/gcp/auth.go
- oci/auth/login/login.go
Part of https://github.com/fluxcd/image-reflector-controller/issues/612
> Add proxy support for oci/auth login

- chartutil/go.mod
- runtime/go.mod
> Update apis/meta version in chartutil and runtime

- .github/workflows/integration-aws.yaml
- .github/workflows/integration-azure.yaml
- .github/workflows/integration-gcp.yaml
Terraform v1.10.0 had a bug in `apply` when reading variables from environment, refer https://github.com/hashicorp/terraform/issues/36106 for details. This resulted in all of our CI setup that uses terraform to fail with the following error:
```
Error: Can't change variable when applying a saved plan
The variable tags cannot be set using the -var and -var-file options when
applying a saved plan file, because a saved plan includes the variable values
that were set when it was created. The saved plan specifies
"{\"environment\"=\"github\", \"ci\"=\"true\", \"repo\"=\"pkg\",
\"createdat\"=\"x2024-12-10_12h09m54s\"}" as the value whereas during apply
the value object with 4 attributes was set by an environment variable. To
declare an ephemeral variable which is not saved in the plan file, use …
```
> workflows: Use setup-terraform install latest

- runtime/events/recorder.go
Allow creating an event recorder without requiring a controller-runtime manager. This is useful when sending events to notification-controller from a client such as the Flux CLI.
> Add event recorder constructor decoupled from runtime Manager

- oci/auth/aws/auth.go
- oci/auth/aws/auth_test.go
Resolves #832 and references https://github.com/awslabs/amazon-ecr-credential-helper/blob/69e8c24e6fc115fd00d7c363cde156570ce73144/ecr-login/api/client.go#L40.
Public AWS Documentation about hidden partitions (non-amazonaws.com or .com.cn) is limited. Read more about AWS partitions [here](https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/partitions.html).
> Update ECR parsing regex to include non-public AWS partitions

- apis/meta/conditions.go
Part of: https://github.com/fluxcd/flux2/pull/5151
Part of: https://github.com/fluxcd/notification-controller/pull/948
> [RFC-0009] Add InvalidCELExpressionReason to apis/meta

- ssa/manager_diff.go
- ssa/manager_diff_test.go
Solving: https://github.com/fluxcd/flux2/issues/5163
Aligns ssa `DiffOptions` to `ApplyOptions` when diffing with `ResourceManager`
Will allow to modify diffing behavior in https://github.com/fluxcd/flux2/blob/e09ba7a8e60eb5f7be633acfee7b6c265244dc09/internal/build/diff.go#L100
to:
```golang
diffOptions := ssa.DiffOptions{
Exclusions: map[string]string{
"kustomize.toolkit.fluxcd.io/reconcile": "disabled",
"kustomize.toolkit.fluxcd.io/ssa":       "ignore",
},
IfNotPresentSelector: map[string]string{
"kustomize.toolkit.fluxcd.io/ssa": "ifnotpresent",
},
}
```
to align to kustomize-controller behavior 
https://github.com/fluxcd/kustomize-controller/blob/59676860b8cb5bb25db94efc7dea8b75f5966998/internal/controller/kustomization_controller.go#L678
> ssa: Align ResourceManager.Diff skipping resources with ResourceManager.Apply

- ssa/changeset.go
This can then be used to improve cardinality of logs in kustomize-controller.
I have tested and will make a PR to kustomize-controller which does this:  
```
log.Info("server-side apply for cluster definitions completed", "output", changeSet.ToMap())
+                       log.Info("server-side apply for cluster definitions completed", "output", changeSet.ToGroupedMap()
```
It helps with https://github.com/fluxcd/flux2/issues/4036
> chore: add function to group entries by action in changeset output

- cache/go.mod
- cache/involved_object.go
- cache/lru.go
- cache/lru_test.go
- cache/store.go
- cache/token.go
- cache/token_test.go
Introduce a cache that is specialized for access tokens. This is a thin abstraction on top of the LRU cache adding requirements that are important for managing the lifetime of tokens:
* We consider tokens expired after 80% of their lifetime. This is what kubelet does for rotating ServiceAccount tokens inside pods ([ref](https://github.com/kubernetes/kubernetes/blob/4032177faf21ae2f99a2012634167def2376b370/pkg/kubelet/token/token_manager.go#L172-L174)).
* We need a pessimistic approach for considering tokens expired. With this in mind we store two time points: the usual `time.Now().Add(duration)`, which has a monotonic clock, and also a Unix time point wihtout a monotonic clock. If either report `t.Before(time.Now()) == true`, the token is considered expired. This is important because Flux …
> Add cache specialized for access tokens

- runtime/cel/expression.go
- runtime/cel/expression_test.go
related: https://github.com/fluxcd/notification-controller/issues/589#issuecomment-2688342204
in order to leverage the `cel` flux package for the purposes of evaluating a commit status/id expression, it's necessary to expose a function for evaluating strings ([similar](https://github.com/fluxcd/pkg/blob/8b1f852228b117123efcc7b5708ce112801416b6/runtime/cel/expression.go#L128) to `EvaluateBoolean`)
> support string evaluation in CEL expressions

- actions/sops/action.yaml
Update the download URL to `getsops/sops` and fix Windows binary name.
> actions: Update SOPS repository

- git/gogit/go.mod
- git/gogit/go.sum
- git/internal/e2e/go.mod
- oci/go.mod
- oci/go.sum
- oci/tests/integration/go.mod
Downgrade `github.com/Masterminds/semver` from v3.3.1 to v3.3.0. The v3.3.0 matches latest stable Helm v3.17.3.
xref:
- https://github.com/fluxcd/source-controller/issues/1738
- https://github.com/Masterminds/semver/issues/258
> Downgrade `Masterminds/semver` to v3.3.0

- auth/gcp/gke_metadata.go
- auth/gcp/options.go
- auth/gcp/provider.go
- auth/gcp/token.go
- auth/gcp/token_source.go
- auth/gcp/token_supplier.go
- auth/go.mod
- auth/go.sum
This PR introduces the `gcp` library from [RFC-0010](https://github.com/fluxcd/flux2/blob/main/rfcs/0010-multi-tenant-workload-identity/README.md).
PR Stack:
* [`azure`](https://github.com/fluxcd/pkg/pull/909)
* `gcp` <---
* [`aws`](https://github.com/fluxcd/pkg/pull/907)
* [`core`](https://github.com/fluxcd/pkg/pull/906)
> [RFC-0010] Add gcp auth library

- auth/aws/implementation.go
- auth/aws/implementation_test.go
- auth/aws/options.go
- auth/aws/options_test.go
- auth/aws/provider.go
- auth/aws/provider_test.go
- auth/azure/implementation.go
- auth/azure/implementation_test.go
- auth/azure/provider.go
- auth/azure/provider_test.go
- auth/gcp/implementation.go
- auth/gcp/implementation_test.go
- auth/gcp/provider.go
- auth/gcp/provider_test.go
- auth/gcp/token_supplier.go
- auth/get_token_test.go
- auth/go.mod
- git/go.mod
- git/gogit/go.mod
- git/internal/e2e/go.mod
- oci/tests/integration/go.mod
> [RFC-0010] Add tests for auth providers

- ssa/changeset.go
- ssa/manager_wait.go
- ssa/manager_wait_test.go
This PR adds a helper function that ca be used in the Flux Garbage Collector to determine when the Kubernetes GC has finalized the objects marked for deletion.
> ssa: Implement `WaitForSetTermination`

- .github/workflows/integration-cleanup.yaml
- auth/aws/provider.go
- auth/aws/provider_test.go
- auth/azure/provider.go
- auth/azure/provider_test.go
- auth/gcp/gke_metadata_test.go
- auth/gcp/options.go
- auth/gcp/provider.go
- auth/gcp/provider_test.go
- auth/get_token.go
- auth/get_token_test.go
- auth/provider.go
- git/go.mod
- git/gogit/go.mod
- git/internal/e2e/go.mod
- oci/go.mod
- oci/tests/integration/go.mod
Only support for non-GKE clusters getting access to GCP resources was missing. To support this we introduce the following service account annotation:
```
gcp.auth.fluxcd.io/workload-identity-provider
```
The value of this annotation must match the following pattern:
```
^https://iam.googleapis.com/projects/\d{1,30}/locations/global/workloadIdentityPools/[^/]{1,100}/providers/[^/]{1,100}$
```
Now for getting access to GCP resources EKS/AKS/`kind` users can annotate their `ServiceAccount` with this new annotation and register the Issuer URL of their cluster in GCP as a Workload Identity Provider following these docs:
https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes
> [RFC-0010] Support cross-cloud object-level workload identity

- apis/meta/conditions.go
- auth/feature_gate.go
- auth/get_token.go
- auth/get_token_test.go
- oci/tests/integration/testapp/main.go
xref: https://github.com/fluxcd/flux2/pull/5354
Usage:
```go
// inside github.com/fluxcd/*-controller.git/internal/features/features.go
func init() {
auth.SetFeatureGates(features)
}
// inside github.com/fluxcd/*-controller.git/main.go
func main() {
// ...
if features.Enabled(auth.FeatureGateObjectLevelWorkloadIdentity) {
auth.EnableObjectLevelWorkloadIdentity()
}
// ...
}
```
> [RFC-0010] Introduce feature gate for enabling object-level workload identity

- auth/gcp/options.go
- auth/gcp/provider_test.go
- oci/tests/integration/gcp_test.go
- oci/tests/integration/go.mod
- oci/tests/integration/job_test.go
- oci/tests/integration/oci_test.go
- oci/tests/integration/suite_test.go
- oci/tests/integration/terraform/gcp/main.tf
- oci/tests/integration/terraform/gcp/outputs.tf
- oci/tests/integration/terraform/gcp/variables.tf
Important fix for GCP WIF. While writing this test I found out that the audience string can't have the `https:` prefix. It needs to start with `//`.
This test is passing locally with my personal GCP account, but for passing in our CI it needs the GCP IAM role [`roles/iam.workloadIdentityPoolAdmin`](https://cloud.google.com/iam/docs/roles-permissions/iam#iam.workloadIdentityPoolAdmin) to be added to the GCP Service Account that we use for applying terraform in the GitHub Action.
@stefanprodan Can you please add this role to the GH Action GCP SA?
Note: We don't need a test like this for the other clouds as the code path is only different for GCP. For AWS and Azure the cross-cloud and same-cloud code path is exactly the same, and for both …
> [RFC-0010] Add integration test for GCP workload identity federation

- auth/aws/provider.go
- auth/aws/provider_test.go
Some helm charts require authentication against the `public.ecr.aws` ECR registery e.g. [aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler).
Current flux v2.6.1 does not allow me to update my aws-node-termination-handler deployment due to this error: 
```
HelmChart 'flux-system/flux-system-aws-node-termination-handler' is not ready: unknown build error: failed to get credential from 'aws': failed to parse artifact repository 'public.ecr.aws/aws-ec2/helm': invalid AWS registry: 'public.ecr.aws'. must match ([0-9+]*).dkr.ecr(?:-fips)?\.([^/.]*)\.(amazonaws\.com[.cn]*|sc2s\.sgov\.gov|c2s\.ic\.gov|cloud\.adc-e\.uk|csp\.hci\.ic\.gov)
```
So this PR fixes that error by making `public.ecr.aws` a valid AWS …
> Introduce authentication for public.ecr.aws

- .github/workflows/integration-azure.yaml
- git/gogit/transport.go
- git/internal/e2e/go.mod
- oci/tests/integration/azure_test.go
- oci/tests/integration/git_test.go
- oci/tests/integration/go.mod
- oci/tests/integration/go.sum
- oci/tests/integration/job_test.go
- oci/tests/integration/suite_test.go
- oci/tests/integration/terraform/azure/outputs.tf
- oci/tests/integration/testapp/main.go
This PR fixes a regression in host key negotiation when the algorithms `rsa-sha2-512` or `rsa-sha2-256` are required.
This regression was introduced in [this](https://github.com/fluxcd/pkg/pull/943) PR, which was a fix for another regression, this one in the `go-git` dependency. Context [here](https://github.com/fluxcd/flux2/issues/5385).
This PR also introduces integration tests for Azure DevOps with SSH, which would have caught the regression this PR is fixing.
> fix: Support rsa-sha2-512 and rsa-sha2-256 host key algos when ssh-rsa is supported

- ssa/manager_apply.go
- ssa/manager_apply_test.go
- ssa/manager_diff.go
- ssa/manager_diff_test.go
- ssa/testdata/test11.yaml
- ssa/utils/cert_validation.go
- ssa/utils/cert_validation_test.go
Fixes #800
- Added a new `cert_validation.go` file in ssa
- This follows the logic / pattern kubernetes uses  [here](https://github.com/kubernetes/kubernetes/commit/04d2f336419b5a824cb96cb88462ef18a90d619d#diff-53f04b012ea2fe7c85175c568131f77d593c637217cfc2fbb6768020b22d3a59R29-R37)
- Will decode from base64 and validate the cert
- Added function `removeCaBundleFromCRD` to `manager_apply.go`
Please let me know if there is some feedback, more tests/specific test cases to add, or a different approach.
> fix: Remove CABundle from CRD objects if the cert is invalid

- runtime/secrets/reader.go
- runtime/secrets/reader_test.go
Addresses https://github.com/fluxcd/notification-controller/pull/1137#discussion_r2180561747
Updates TLSConfigFromSecret function to retrieve logger from context using log.FromContext(ctx) instead of accepting logger as a parameter, aligning with Flux's standard pattern.
> runtime/secrets: use context-based logger retrieval

- ssa/manager_apply.go
- ssa/testdata/test12.yaml
Use the `WaitForSet` to correctly health check cluster-level objects.
> ssa: Fix waiting for classes in `ApplyAllStaged`

- runtime/secrets/applier.go
- runtime/secrets/applier_test.go
- runtime/secrets/converter.go
- runtime/secrets/converter_test.go
- runtime/secrets/error.go
- runtime/secrets/factory.go
- runtime/secrets/factory_test.go
- runtime/secrets/reader_test.go
- runtime/secrets/secrets.go
- runtime/secrets/secrets_test.go
- runtime/secrets/suite_test.go
Implement `MakeGitHubAppSecret`, `MakeSSHSecret` and add tests.
In addition, this PR adds a helper for applying secrets with Kubernetes SSA.
> runtime/secrets: Add `MakeGitHubAppSecret` & `MakeSSHSecret`

- cmd/cli/pkg_prepare_release.go
- cmd/cli/pkg_release.go
- cmd/internal/compute_module_bumps.go
When changing something in the `git` module, both `git` and `git/gogit` should be released because `git/gogit` depends on `git`. Even if `git/gogit` has not changed between its latest tag and HEAD, it should still be released because it received the bump of `git`.
This PR fixes this edge case:
```
make prep
Bumped git: 0.33.0 => 0.34.0 in modules: git/gogit, git/internal/e2e, oci/tests/integration
Bumped git/gogit: 0.36.0 => 0.37.0 in modules: git/internal/e2e, oci/tests/integration
Confirm applying changes above to file system? (Y/n, only uppercase Y will confirm)
n
Aborting changes.
```
> tools: Fix module bump detection for bumps that cause other bumps

- runtime/secrets/factory.go
- runtime/secrets/factory_test.go
- runtime/secrets/secrets.go
The generated secrets were missing `apiVersion` and `kind`.
> runtime/secrets: Set GVK on generated secrets

- oci/tests/integration/go.mod
- runtime/controller/watch.go
- runtime/controller/watch_test.go
Part of: https://github.com/fluxcd/flux2/issues/5446
> runtime/controller: Fix watch configs for empty label selector

- runtime/controller/watch_test.go
Part of: https://github.com/fluxcd/flux2/issues/5446
> runtime/controller: Add test case for watching all configs except helm storage

- oci/tests/integration/go.mod
- runtime/secrets/converter.go
- runtime/secrets/converter_test.go
- runtime/secrets/secrets.go
Add `TokenAuth` detection support to `AuthMethodsFromSecret`. This was missing from #983 when `AuthMethodsFromSecret` was added - generic token authentication detection was overlooked.
Also simplify `BearerAuth` and `TokenAuth` from struct to string type since they don't need struct wrapping.
> runtime/secrets: add TokenAuth detection support

- chartutil/encode.go
- chartutil/go.mod
- chartutil/sort.go
- chartutil/sort_test.go
With chart values that contain double nested slices, sort will fail.
This patch contains:
- a test that contain a map with double nested slices
- a fix for this bug.
Without this patch, this will fail:
```
{
"a": [[
"p": "v-p"
"r": "v-r"
"q": v-q"
]]
}
```
> chartutil: Fix sort not recursing for slices

- oci/tests/integration/go.mod
- runtime/secrets/converter.go
- runtime/secrets/converter_test.go
- runtime/secrets/secrets.go
ref: fluxcd/flux2#5433
Adds functional options to support different CA certificate handling modes in runtime/secrets package.
Flux controllers currently use different CA certificate handling approaches:
- **source-controller**: Extend mode (System CAs + user CA) - https://github.com/fluxcd/source-controller/blob/v1.6.0/internal/tls/config.go#L136
- **notification-controller**: Replace mode (user CA only) - https://github.com/fluxcd/notification-controller/blob/v1.6.0/internal/server/event_handlers.go#L388-L392  
- **image-reflector-controller**: Extend mode (System CAs + user CA) - https://github.com/fluxcd/image-reflector-controller/blob/v0.35.0/internal/secret/secret.go#L121-L129
This inconsistency prevents using a unified secrets package across all Flux components.
- …
> runtime/secrets: add WithSystemCertPool for CA handling

- oci/tests/integration/go.mod
- runtime/secrets/reader.go
- runtime/secrets/reader_test.go
follow-up PR for #995 .
I forgot to update the TLSConfigFromSecretRef function in #995 🙇
> runtime/secrets: add TLSConfigOption support to TLSConfigFromSecretRef

- git/github/client.go
- git/github/client_test.go
- git/gogit/go.mod
- git/internal/e2e/go.mod
- oci/tests/integration/go.mod
This commit ensures if available, a custom ca.crt is appended to system cert pool and set to the github app transport tls configuration.
closes #998
> git/github: Add support for mTLS to GitHub App transport

- auth/options.go
- auth/options_test.go
- oci/tests/integration/go.mod
Following https://github.com/fluxcd/pkg/pull/1000#issuecomment-3160477432, add timeout setting only.
The `GetHTTPClient()` method now always returns an HTTP client with a 10-second timeout to prevent indefinite hangs during token acquisition from cloud provider STS services.
> auth: add 10-second timeout to HTTP client for token acquisition

- auth/azure/options.go
- auth/azure/provider.go
- auth/azure/provider_test.go
Fixes: https://github.com/fluxcd/pkg/issues/996
Changes include:
- Read Azure endpoint configuration from JSON file.
- JSON file path is configured via AZURE_ENVIRONMENT_FILEPATH env variable.
- Unit tests.
Test behavior:
1. Environment variable specified but file doesn't exist.
```
- lastTransitionTime: "2025-08-06T18:25:09Z"
message: 'failed to get credential from azure: failed to get container registry
suffix from environment file: open /etc/cloud/cloud-config.json: no such file
or directory'
observedGeneration: 2
reason: AuthenticationFailed
status: "False"
type: Ready
```
2. Environment variable and filepath exist but does not contain ARM endpoint/Token audience specified.
```
- lastTransitionTime: "2025-08-06T17:56:55Z"
message: 'failed to get credential from azure: …
```
> auth/azure: Add support for custom Azure cloud configurations

- artifact/config/flags.go
- artifact/config/flags_test.go
Changes:
- `--storage-address` -> `storage-addr`
- `--storage-adv-address` -> `storage-adv-addr`
> artifact: Set address flags to match source-controller

- runtime/secrets/converter.go
- runtime/secrets/converter_test.go
- tests/integration/go.mod
ref: https://github.com/fluxcd/notification-controller/pull/1190
While reviewing the negative diff in that PR, I noticed that the `address` key in the secret referenced by proxySecretRef is missing some validations.
> runtime/secrets: validate proxy URL scheme and length
